#pragma once

#define IDI_PAO_DE_KUAI 101

#define IDR_POKER_CARDS 201

#define IDR_WAV_UI_BUTTON_CLICK 301
#define IDR_WAV_UI_CONFIRM 302
#define IDR_WAV_UI_CANCEL 303
#define IDR_WAV_UI_TOAST 304
#define IDR_WAV_UI_PAUSE 305
#define IDR_WAV_UI_RESUME 306
#define IDR_WAV_CARD_SELECT 307
#define IDR_WAV_CARD_DESELECT 308
#define IDR_WAV_CARD_DEAL 309
#define IDR_WAV_CARD_PLAY 310
#define IDR_WAV_CARD_PASS 311
#define IDR_WAV_CARD_HINT 312
#define IDR_WAV_GAME_INVALID_MOVE 313
#define IDR_WAV_GAME_TURN_PROMPT 314
#define IDR_WAV_GAME_ROUND_START 315
#define IDR_WAV_GAME_ROUND_END 316
#define IDR_WAV_EVENT_BOMB 317
#define IDR_WAV_EVENT_SPRING 318
#define IDR_WAV_EVENT_WIN 319
#define IDR_WAV_EVENT_LOSE 320
#define IDR_WAV_EVENT_AI_TALK 321
