/* AUTO-GENERATED by tools/gen_com_shim.py -- do not edit by hand.
 * Regenerate with: python tools/gen_com_shim.py
 * Source of truth: MinGW-w64 C-mode SDK headers; layout is verified at
 * compile time by tests/shim_layout (MinGW) -- see plan.md 3.3.
 */
/* Included by tests/shim_layout after <d2d1.h>, <dwrite.h> and
 * PDK_SKIP_DWRITE_TYPES + graphics/d2d_c.h.  MinGW only. */
#include <stddef.h>

/* ID2D1Factory: 17 slots */
_Static_assert(sizeof(PDK_ID2D1FactoryVtbl) == sizeof(ID2D1FactoryVtbl), "ID2D1Factory vtable size");
typedef char pdk_off_ID2D1Factory_ReloadSystemMetrics[offsetof(PDK_ID2D1FactoryVtbl, ReloadSystemMetrics) == offsetof(ID2D1FactoryVtbl, ReloadSystemMetrics) ? 1 : -1];
typedef char pdk_off_ID2D1Factory_GetDesktopDpi[offsetof(PDK_ID2D1FactoryVtbl, GetDesktopDpi) == offsetof(ID2D1FactoryVtbl, GetDesktopDpi) ? 1 : -1];
typedef char pdk_off_ID2D1Factory_CreateRectangleGeometry[offsetof(PDK_ID2D1FactoryVtbl, CreateRectangleGeometry) == offsetof(ID2D1FactoryVtbl, CreateRectangleGeometry) ? 1 : -1];
typedef char pdk_off_ID2D1Factory_CreateRoundedRectangleGeometry[offsetof(PDK_ID2D1FactoryVtbl, CreateRoundedRectangleGeometry) == offsetof(ID2D1FactoryVtbl, CreateRoundedRectangleGeometry) ? 1 : -1];
typedef char pdk_off_ID2D1Factory_CreateEllipseGeometry[offsetof(PDK_ID2D1FactoryVtbl, CreateEllipseGeometry) == offsetof(ID2D1FactoryVtbl, CreateEllipseGeometry) ? 1 : -1];
typedef char pdk_off_ID2D1Factory_CreateGeometryGroup[offsetof(PDK_ID2D1FactoryVtbl, CreateGeometryGroup) == offsetof(ID2D1FactoryVtbl, CreateGeometryGroup) ? 1 : -1];
typedef char pdk_off_ID2D1Factory_CreateTransformedGeometry[offsetof(PDK_ID2D1FactoryVtbl, CreateTransformedGeometry) == offsetof(ID2D1FactoryVtbl, CreateTransformedGeometry) ? 1 : -1];
typedef char pdk_off_ID2D1Factory_CreatePathGeometry[offsetof(PDK_ID2D1FactoryVtbl, CreatePathGeometry) == offsetof(ID2D1FactoryVtbl, CreatePathGeometry) ? 1 : -1];
typedef char pdk_off_ID2D1Factory_CreateStrokeStyle[offsetof(PDK_ID2D1FactoryVtbl, CreateStrokeStyle) == offsetof(ID2D1FactoryVtbl, CreateStrokeStyle) ? 1 : -1];
typedef char pdk_off_ID2D1Factory_CreateDrawingStateBlock[offsetof(PDK_ID2D1FactoryVtbl, CreateDrawingStateBlock) == offsetof(ID2D1FactoryVtbl, CreateDrawingStateBlock) ? 1 : -1];
typedef char pdk_off_ID2D1Factory_CreateWicBitmapRenderTarget[offsetof(PDK_ID2D1FactoryVtbl, CreateWicBitmapRenderTarget) == offsetof(ID2D1FactoryVtbl, CreateWicBitmapRenderTarget) ? 1 : -1];
typedef char pdk_off_ID2D1Factory_CreateHwndRenderTarget[offsetof(PDK_ID2D1FactoryVtbl, CreateHwndRenderTarget) == offsetof(ID2D1FactoryVtbl, CreateHwndRenderTarget) ? 1 : -1];
typedef char pdk_off_ID2D1Factory_CreateDxgiSurfaceRenderTarget[offsetof(PDK_ID2D1FactoryVtbl, CreateDxgiSurfaceRenderTarget) == offsetof(ID2D1FactoryVtbl, CreateDxgiSurfaceRenderTarget) ? 1 : -1];
typedef char pdk_off_ID2D1Factory_CreateDCRenderTarget[offsetof(PDK_ID2D1FactoryVtbl, CreateDCRenderTarget) == offsetof(ID2D1FactoryVtbl, CreateDCRenderTarget) ? 1 : -1];

/* ID2D1Resource: 4 slots */
_Static_assert(sizeof(PDK_ID2D1ResourceVtbl) == sizeof(ID2D1ResourceVtbl), "ID2D1Resource vtable size");
typedef char pdk_off_ID2D1Resource_GetFactory[offsetof(PDK_ID2D1ResourceVtbl, GetFactory) == offsetof(ID2D1ResourceVtbl, GetFactory) ? 1 : -1];

/* ID2D1RenderTarget: 57 slots */
_Static_assert(sizeof(PDK_ID2D1RenderTargetVtbl) == sizeof(ID2D1RenderTargetVtbl), "ID2D1RenderTarget vtable size");
typedef char pdk_off_ID2D1RenderTarget_CreateBitmap[offsetof(PDK_ID2D1RenderTargetVtbl, CreateBitmap) == offsetof(ID2D1RenderTargetVtbl, CreateBitmap) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_CreateBitmapFromWicBitmap[offsetof(PDK_ID2D1RenderTargetVtbl, CreateBitmapFromWicBitmap) == offsetof(ID2D1RenderTargetVtbl, CreateBitmapFromWicBitmap) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_CreateSharedBitmap[offsetof(PDK_ID2D1RenderTargetVtbl, CreateSharedBitmap) == offsetof(ID2D1RenderTargetVtbl, CreateSharedBitmap) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_CreateBitmapBrush[offsetof(PDK_ID2D1RenderTargetVtbl, CreateBitmapBrush) == offsetof(ID2D1RenderTargetVtbl, CreateBitmapBrush) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_CreateSolidColorBrush[offsetof(PDK_ID2D1RenderTargetVtbl, CreateSolidColorBrush) == offsetof(ID2D1RenderTargetVtbl, CreateSolidColorBrush) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_CreateGradientStopCollection[offsetof(PDK_ID2D1RenderTargetVtbl, CreateGradientStopCollection) == offsetof(ID2D1RenderTargetVtbl, CreateGradientStopCollection) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_CreateLinearGradientBrush[offsetof(PDK_ID2D1RenderTargetVtbl, CreateLinearGradientBrush) == offsetof(ID2D1RenderTargetVtbl, CreateLinearGradientBrush) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_CreateRadialGradientBrush[offsetof(PDK_ID2D1RenderTargetVtbl, CreateRadialGradientBrush) == offsetof(ID2D1RenderTargetVtbl, CreateRadialGradientBrush) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_CreateCompatibleRenderTarget[offsetof(PDK_ID2D1RenderTargetVtbl, CreateCompatibleRenderTarget) == offsetof(ID2D1RenderTargetVtbl, CreateCompatibleRenderTarget) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_CreateLayer[offsetof(PDK_ID2D1RenderTargetVtbl, CreateLayer) == offsetof(ID2D1RenderTargetVtbl, CreateLayer) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_CreateMesh[offsetof(PDK_ID2D1RenderTargetVtbl, CreateMesh) == offsetof(ID2D1RenderTargetVtbl, CreateMesh) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_DrawLine[offsetof(PDK_ID2D1RenderTargetVtbl, DrawLine) == offsetof(ID2D1RenderTargetVtbl, DrawLine) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_DrawRectangle[offsetof(PDK_ID2D1RenderTargetVtbl, DrawRectangle) == offsetof(ID2D1RenderTargetVtbl, DrawRectangle) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_FillRectangle[offsetof(PDK_ID2D1RenderTargetVtbl, FillRectangle) == offsetof(ID2D1RenderTargetVtbl, FillRectangle) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_DrawRoundedRectangle[offsetof(PDK_ID2D1RenderTargetVtbl, DrawRoundedRectangle) == offsetof(ID2D1RenderTargetVtbl, DrawRoundedRectangle) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_FillRoundedRectangle[offsetof(PDK_ID2D1RenderTargetVtbl, FillRoundedRectangle) == offsetof(ID2D1RenderTargetVtbl, FillRoundedRectangle) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_DrawEllipse[offsetof(PDK_ID2D1RenderTargetVtbl, DrawEllipse) == offsetof(ID2D1RenderTargetVtbl, DrawEllipse) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_FillEllipse[offsetof(PDK_ID2D1RenderTargetVtbl, FillEllipse) == offsetof(ID2D1RenderTargetVtbl, FillEllipse) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_DrawGeometry[offsetof(PDK_ID2D1RenderTargetVtbl, DrawGeometry) == offsetof(ID2D1RenderTargetVtbl, DrawGeometry) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_FillGeometry[offsetof(PDK_ID2D1RenderTargetVtbl, FillGeometry) == offsetof(ID2D1RenderTargetVtbl, FillGeometry) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_FillMesh[offsetof(PDK_ID2D1RenderTargetVtbl, FillMesh) == offsetof(ID2D1RenderTargetVtbl, FillMesh) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_FillOpacityMask[offsetof(PDK_ID2D1RenderTargetVtbl, FillOpacityMask) == offsetof(ID2D1RenderTargetVtbl, FillOpacityMask) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_DrawBitmap[offsetof(PDK_ID2D1RenderTargetVtbl, DrawBitmap) == offsetof(ID2D1RenderTargetVtbl, DrawBitmap) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_DrawText[offsetof(PDK_ID2D1RenderTargetVtbl, DrawText) == offsetof(ID2D1RenderTargetVtbl, DrawText) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_DrawTextLayout[offsetof(PDK_ID2D1RenderTargetVtbl, DrawTextLayout) == offsetof(ID2D1RenderTargetVtbl, DrawTextLayout) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_DrawGlyphRun[offsetof(PDK_ID2D1RenderTargetVtbl, DrawGlyphRun) == offsetof(ID2D1RenderTargetVtbl, DrawGlyphRun) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_SetTransform[offsetof(PDK_ID2D1RenderTargetVtbl, SetTransform) == offsetof(ID2D1RenderTargetVtbl, SetTransform) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_GetTransform[offsetof(PDK_ID2D1RenderTargetVtbl, GetTransform) == offsetof(ID2D1RenderTargetVtbl, GetTransform) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_SetAntialiasMode[offsetof(PDK_ID2D1RenderTargetVtbl, SetAntialiasMode) == offsetof(ID2D1RenderTargetVtbl, SetAntialiasMode) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_GetAntialiasMode[offsetof(PDK_ID2D1RenderTargetVtbl, GetAntialiasMode) == offsetof(ID2D1RenderTargetVtbl, GetAntialiasMode) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_SetTextAntialiasMode[offsetof(PDK_ID2D1RenderTargetVtbl, SetTextAntialiasMode) == offsetof(ID2D1RenderTargetVtbl, SetTextAntialiasMode) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_GetTextAntialiasMode[offsetof(PDK_ID2D1RenderTargetVtbl, GetTextAntialiasMode) == offsetof(ID2D1RenderTargetVtbl, GetTextAntialiasMode) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_SetTextRenderingParams[offsetof(PDK_ID2D1RenderTargetVtbl, SetTextRenderingParams) == offsetof(ID2D1RenderTargetVtbl, SetTextRenderingParams) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_GetTextRenderingParams[offsetof(PDK_ID2D1RenderTargetVtbl, GetTextRenderingParams) == offsetof(ID2D1RenderTargetVtbl, GetTextRenderingParams) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_SetTags[offsetof(PDK_ID2D1RenderTargetVtbl, SetTags) == offsetof(ID2D1RenderTargetVtbl, SetTags) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_GetTags[offsetof(PDK_ID2D1RenderTargetVtbl, GetTags) == offsetof(ID2D1RenderTargetVtbl, GetTags) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_PushLayer[offsetof(PDK_ID2D1RenderTargetVtbl, PushLayer) == offsetof(ID2D1RenderTargetVtbl, PushLayer) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_PopLayer[offsetof(PDK_ID2D1RenderTargetVtbl, PopLayer) == offsetof(ID2D1RenderTargetVtbl, PopLayer) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_Flush[offsetof(PDK_ID2D1RenderTargetVtbl, Flush) == offsetof(ID2D1RenderTargetVtbl, Flush) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_SaveDrawingState[offsetof(PDK_ID2D1RenderTargetVtbl, SaveDrawingState) == offsetof(ID2D1RenderTargetVtbl, SaveDrawingState) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_RestoreDrawingState[offsetof(PDK_ID2D1RenderTargetVtbl, RestoreDrawingState) == offsetof(ID2D1RenderTargetVtbl, RestoreDrawingState) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_PushAxisAlignedClip[offsetof(PDK_ID2D1RenderTargetVtbl, PushAxisAlignedClip) == offsetof(ID2D1RenderTargetVtbl, PushAxisAlignedClip) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_PopAxisAlignedClip[offsetof(PDK_ID2D1RenderTargetVtbl, PopAxisAlignedClip) == offsetof(ID2D1RenderTargetVtbl, PopAxisAlignedClip) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_Clear[offsetof(PDK_ID2D1RenderTargetVtbl, Clear) == offsetof(ID2D1RenderTargetVtbl, Clear) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_BeginDraw[offsetof(PDK_ID2D1RenderTargetVtbl, BeginDraw) == offsetof(ID2D1RenderTargetVtbl, BeginDraw) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_EndDraw[offsetof(PDK_ID2D1RenderTargetVtbl, EndDraw) == offsetof(ID2D1RenderTargetVtbl, EndDraw) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_GetPixelFormat[offsetof(PDK_ID2D1RenderTargetVtbl, GetPixelFormat) == offsetof(ID2D1RenderTargetVtbl, GetPixelFormat) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_SetDpi[offsetof(PDK_ID2D1RenderTargetVtbl, SetDpi) == offsetof(ID2D1RenderTargetVtbl, SetDpi) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_GetDpi[offsetof(PDK_ID2D1RenderTargetVtbl, GetDpi) == offsetof(ID2D1RenderTargetVtbl, GetDpi) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_GetSize[offsetof(PDK_ID2D1RenderTargetVtbl, GetSize) == offsetof(ID2D1RenderTargetVtbl, GetSize) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_GetPixelSize[offsetof(PDK_ID2D1RenderTargetVtbl, GetPixelSize) == offsetof(ID2D1RenderTargetVtbl, GetPixelSize) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_GetMaximumBitmapSize[offsetof(PDK_ID2D1RenderTargetVtbl, GetMaximumBitmapSize) == offsetof(ID2D1RenderTargetVtbl, GetMaximumBitmapSize) ? 1 : -1];
typedef char pdk_off_ID2D1RenderTarget_IsSupported[offsetof(PDK_ID2D1RenderTargetVtbl, IsSupported) == offsetof(ID2D1RenderTargetVtbl, IsSupported) ? 1 : -1];

/* ID2D1HwndRenderTarget: 60 slots */
_Static_assert(sizeof(PDK_ID2D1HwndRenderTargetVtbl) == sizeof(ID2D1HwndRenderTargetVtbl), "ID2D1HwndRenderTarget vtable size");
typedef char pdk_off_ID2D1HwndRenderTarget_CheckWindowState[offsetof(PDK_ID2D1HwndRenderTargetVtbl, CheckWindowState) == offsetof(ID2D1HwndRenderTargetVtbl, CheckWindowState) ? 1 : -1];
typedef char pdk_off_ID2D1HwndRenderTarget_Resize[offsetof(PDK_ID2D1HwndRenderTargetVtbl, Resize) == offsetof(ID2D1HwndRenderTargetVtbl, Resize) ? 1 : -1];
typedef char pdk_off_ID2D1HwndRenderTarget_GetHwnd[offsetof(PDK_ID2D1HwndRenderTargetVtbl, GetHwnd) == offsetof(ID2D1HwndRenderTargetVtbl, GetHwnd) ? 1 : -1];

/* ID2D1Brush: 8 slots */
_Static_assert(sizeof(PDK_ID2D1BrushVtbl) == sizeof(ID2D1BrushVtbl), "ID2D1Brush vtable size");
typedef char pdk_off_ID2D1Brush_SetOpacity[offsetof(PDK_ID2D1BrushVtbl, SetOpacity) == offsetof(ID2D1BrushVtbl, SetOpacity) ? 1 : -1];
typedef char pdk_off_ID2D1Brush_SetTransform[offsetof(PDK_ID2D1BrushVtbl, SetTransform) == offsetof(ID2D1BrushVtbl, SetTransform) ? 1 : -1];
typedef char pdk_off_ID2D1Brush_GetOpacity[offsetof(PDK_ID2D1BrushVtbl, GetOpacity) == offsetof(ID2D1BrushVtbl, GetOpacity) ? 1 : -1];
typedef char pdk_off_ID2D1Brush_GetTransform[offsetof(PDK_ID2D1BrushVtbl, GetTransform) == offsetof(ID2D1BrushVtbl, GetTransform) ? 1 : -1];

/* ID2D1SolidColorBrush: 10 slots */
_Static_assert(sizeof(PDK_ID2D1SolidColorBrushVtbl) == sizeof(ID2D1SolidColorBrushVtbl), "ID2D1SolidColorBrush vtable size");
typedef char pdk_off_ID2D1SolidColorBrush_SetColor[offsetof(PDK_ID2D1SolidColorBrushVtbl, SetColor) == offsetof(ID2D1SolidColorBrushVtbl, SetColor) ? 1 : -1];
typedef char pdk_off_ID2D1SolidColorBrush_GetColor[offsetof(PDK_ID2D1SolidColorBrushVtbl, GetColor) == offsetof(ID2D1SolidColorBrushVtbl, GetColor) ? 1 : -1];

/* ID2D1LinearGradientBrush: 13 slots */
_Static_assert(sizeof(PDK_ID2D1LinearGradientBrushVtbl) == sizeof(ID2D1LinearGradientBrushVtbl), "ID2D1LinearGradientBrush vtable size");
typedef char pdk_off_ID2D1LinearGradientBrush_SetStartPoint[offsetof(PDK_ID2D1LinearGradientBrushVtbl, SetStartPoint) == offsetof(ID2D1LinearGradientBrushVtbl, SetStartPoint) ? 1 : -1];
typedef char pdk_off_ID2D1LinearGradientBrush_SetEndPoint[offsetof(PDK_ID2D1LinearGradientBrushVtbl, SetEndPoint) == offsetof(ID2D1LinearGradientBrushVtbl, SetEndPoint) ? 1 : -1];
typedef char pdk_off_ID2D1LinearGradientBrush_GetStartPoint[offsetof(PDK_ID2D1LinearGradientBrushVtbl, GetStartPoint) == offsetof(ID2D1LinearGradientBrushVtbl, GetStartPoint) ? 1 : -1];
typedef char pdk_off_ID2D1LinearGradientBrush_GetEndPoint[offsetof(PDK_ID2D1LinearGradientBrushVtbl, GetEndPoint) == offsetof(ID2D1LinearGradientBrushVtbl, GetEndPoint) ? 1 : -1];
typedef char pdk_off_ID2D1LinearGradientBrush_GetGradientStopCollection[offsetof(PDK_ID2D1LinearGradientBrushVtbl, GetGradientStopCollection) == offsetof(ID2D1LinearGradientBrushVtbl, GetGradientStopCollection) ? 1 : -1];

/* ID2D1RadialGradientBrush: 17 slots */
_Static_assert(sizeof(PDK_ID2D1RadialGradientBrushVtbl) == sizeof(ID2D1RadialGradientBrushVtbl), "ID2D1RadialGradientBrush vtable size");
typedef char pdk_off_ID2D1RadialGradientBrush_SetCenter[offsetof(PDK_ID2D1RadialGradientBrushVtbl, SetCenter) == offsetof(ID2D1RadialGradientBrushVtbl, SetCenter) ? 1 : -1];
typedef char pdk_off_ID2D1RadialGradientBrush_SetGradientOriginOffset[offsetof(PDK_ID2D1RadialGradientBrushVtbl, SetGradientOriginOffset) == offsetof(ID2D1RadialGradientBrushVtbl, SetGradientOriginOffset) ? 1 : -1];
typedef char pdk_off_ID2D1RadialGradientBrush_SetRadiusX[offsetof(PDK_ID2D1RadialGradientBrushVtbl, SetRadiusX) == offsetof(ID2D1RadialGradientBrushVtbl, SetRadiusX) ? 1 : -1];
typedef char pdk_off_ID2D1RadialGradientBrush_SetRadiusY[offsetof(PDK_ID2D1RadialGradientBrushVtbl, SetRadiusY) == offsetof(ID2D1RadialGradientBrushVtbl, SetRadiusY) ? 1 : -1];
typedef char pdk_off_ID2D1RadialGradientBrush_GetCenter[offsetof(PDK_ID2D1RadialGradientBrushVtbl, GetCenter) == offsetof(ID2D1RadialGradientBrushVtbl, GetCenter) ? 1 : -1];
typedef char pdk_off_ID2D1RadialGradientBrush_GetGradientOriginOffset[offsetof(PDK_ID2D1RadialGradientBrushVtbl, GetGradientOriginOffset) == offsetof(ID2D1RadialGradientBrushVtbl, GetGradientOriginOffset) ? 1 : -1];
typedef char pdk_off_ID2D1RadialGradientBrush_GetRadiusX[offsetof(PDK_ID2D1RadialGradientBrushVtbl, GetRadiusX) == offsetof(ID2D1RadialGradientBrushVtbl, GetRadiusX) ? 1 : -1];
typedef char pdk_off_ID2D1RadialGradientBrush_GetRadiusY[offsetof(PDK_ID2D1RadialGradientBrushVtbl, GetRadiusY) == offsetof(ID2D1RadialGradientBrushVtbl, GetRadiusY) ? 1 : -1];
typedef char pdk_off_ID2D1RadialGradientBrush_GetGradientStopCollection[offsetof(PDK_ID2D1RadialGradientBrushVtbl, GetGradientStopCollection) == offsetof(ID2D1RadialGradientBrushVtbl, GetGradientStopCollection) ? 1 : -1];

/* ID2D1BitmapBrush: 16 slots */
_Static_assert(sizeof(PDK_ID2D1BitmapBrushVtbl) == sizeof(ID2D1BitmapBrushVtbl), "ID2D1BitmapBrush vtable size");
typedef char pdk_off_ID2D1BitmapBrush_SetExtendModeX[offsetof(PDK_ID2D1BitmapBrushVtbl, SetExtendModeX) == offsetof(ID2D1BitmapBrushVtbl, SetExtendModeX) ? 1 : -1];
typedef char pdk_off_ID2D1BitmapBrush_SetExtendModeY[offsetof(PDK_ID2D1BitmapBrushVtbl, SetExtendModeY) == offsetof(ID2D1BitmapBrushVtbl, SetExtendModeY) ? 1 : -1];
typedef char pdk_off_ID2D1BitmapBrush_SetInterpolationMode[offsetof(PDK_ID2D1BitmapBrushVtbl, SetInterpolationMode) == offsetof(ID2D1BitmapBrushVtbl, SetInterpolationMode) ? 1 : -1];
typedef char pdk_off_ID2D1BitmapBrush_SetBitmap[offsetof(PDK_ID2D1BitmapBrushVtbl, SetBitmap) == offsetof(ID2D1BitmapBrushVtbl, SetBitmap) ? 1 : -1];
typedef char pdk_off_ID2D1BitmapBrush_GetExtendModeX[offsetof(PDK_ID2D1BitmapBrushVtbl, GetExtendModeX) == offsetof(ID2D1BitmapBrushVtbl, GetExtendModeX) ? 1 : -1];
typedef char pdk_off_ID2D1BitmapBrush_GetExtendModeY[offsetof(PDK_ID2D1BitmapBrushVtbl, GetExtendModeY) == offsetof(ID2D1BitmapBrushVtbl, GetExtendModeY) ? 1 : -1];
typedef char pdk_off_ID2D1BitmapBrush_GetInterpolationMode[offsetof(PDK_ID2D1BitmapBrushVtbl, GetInterpolationMode) == offsetof(ID2D1BitmapBrushVtbl, GetInterpolationMode) ? 1 : -1];
typedef char pdk_off_ID2D1BitmapBrush_GetBitmap[offsetof(PDK_ID2D1BitmapBrushVtbl, GetBitmap) == offsetof(ID2D1BitmapBrushVtbl, GetBitmap) ? 1 : -1];

/* ID2D1Image: 4 slots */
_Static_assert(sizeof(PDK_ID2D1ImageVtbl) == sizeof(ID2D1ImageVtbl), "ID2D1Image vtable size");

/* ID2D1Bitmap: 11 slots */
_Static_assert(sizeof(PDK_ID2D1BitmapVtbl) == sizeof(ID2D1BitmapVtbl), "ID2D1Bitmap vtable size");
typedef char pdk_off_ID2D1Bitmap_GetSize[offsetof(PDK_ID2D1BitmapVtbl, GetSize) == offsetof(ID2D1BitmapVtbl, GetSize) ? 1 : -1];
typedef char pdk_off_ID2D1Bitmap_GetPixelSize[offsetof(PDK_ID2D1BitmapVtbl, GetPixelSize) == offsetof(ID2D1BitmapVtbl, GetPixelSize) ? 1 : -1];
typedef char pdk_off_ID2D1Bitmap_GetPixelFormat[offsetof(PDK_ID2D1BitmapVtbl, GetPixelFormat) == offsetof(ID2D1BitmapVtbl, GetPixelFormat) ? 1 : -1];
typedef char pdk_off_ID2D1Bitmap_GetDpi[offsetof(PDK_ID2D1BitmapVtbl, GetDpi) == offsetof(ID2D1BitmapVtbl, GetDpi) ? 1 : -1];
typedef char pdk_off_ID2D1Bitmap_CopyFromBitmap[offsetof(PDK_ID2D1BitmapVtbl, CopyFromBitmap) == offsetof(ID2D1BitmapVtbl, CopyFromBitmap) ? 1 : -1];
typedef char pdk_off_ID2D1Bitmap_CopyFromRenderTarget[offsetof(PDK_ID2D1BitmapVtbl, CopyFromRenderTarget) == offsetof(ID2D1BitmapVtbl, CopyFromRenderTarget) ? 1 : -1];
typedef char pdk_off_ID2D1Bitmap_CopyFromMemory[offsetof(PDK_ID2D1BitmapVtbl, CopyFromMemory) == offsetof(ID2D1BitmapVtbl, CopyFromMemory) ? 1 : -1];

/* ID2D1GradientStopCollection: 8 slots */
_Static_assert(sizeof(PDK_ID2D1GradientStopCollectionVtbl) == sizeof(ID2D1GradientStopCollectionVtbl), "ID2D1GradientStopCollection vtable size");
typedef char pdk_off_ID2D1GradientStopCollection_GetGradientStopCount[offsetof(PDK_ID2D1GradientStopCollectionVtbl, GetGradientStopCount) == offsetof(ID2D1GradientStopCollectionVtbl, GetGradientStopCount) ? 1 : -1];
typedef char pdk_off_ID2D1GradientStopCollection_GetGradientStops[offsetof(PDK_ID2D1GradientStopCollectionVtbl, GetGradientStops) == offsetof(ID2D1GradientStopCollectionVtbl, GetGradientStops) ? 1 : -1];
typedef char pdk_off_ID2D1GradientStopCollection_GetColorInterpolationGamma[offsetof(PDK_ID2D1GradientStopCollectionVtbl, GetColorInterpolationGamma) == offsetof(ID2D1GradientStopCollectionVtbl, GetColorInterpolationGamma) ? 1 : -1];
typedef char pdk_off_ID2D1GradientStopCollection_GetExtendMode[offsetof(PDK_ID2D1GradientStopCollectionVtbl, GetExtendMode) == offsetof(ID2D1GradientStopCollectionVtbl, GetExtendMode) ? 1 : -1];

/* ID2D1StrokeStyle: 13 slots */
_Static_assert(sizeof(PDK_ID2D1StrokeStyleVtbl) == sizeof(ID2D1StrokeStyleVtbl), "ID2D1StrokeStyle vtable size");
typedef char pdk_off_ID2D1StrokeStyle_GetStartCap[offsetof(PDK_ID2D1StrokeStyleVtbl, GetStartCap) == offsetof(ID2D1StrokeStyleVtbl, GetStartCap) ? 1 : -1];
typedef char pdk_off_ID2D1StrokeStyle_GetEndCap[offsetof(PDK_ID2D1StrokeStyleVtbl, GetEndCap) == offsetof(ID2D1StrokeStyleVtbl, GetEndCap) ? 1 : -1];
typedef char pdk_off_ID2D1StrokeStyle_GetDashCap[offsetof(PDK_ID2D1StrokeStyleVtbl, GetDashCap) == offsetof(ID2D1StrokeStyleVtbl, GetDashCap) ? 1 : -1];
typedef char pdk_off_ID2D1StrokeStyle_GetMiterLimit[offsetof(PDK_ID2D1StrokeStyleVtbl, GetMiterLimit) == offsetof(ID2D1StrokeStyleVtbl, GetMiterLimit) ? 1 : -1];
typedef char pdk_off_ID2D1StrokeStyle_GetLineJoin[offsetof(PDK_ID2D1StrokeStyleVtbl, GetLineJoin) == offsetof(ID2D1StrokeStyleVtbl, GetLineJoin) ? 1 : -1];
typedef char pdk_off_ID2D1StrokeStyle_GetDashOffset[offsetof(PDK_ID2D1StrokeStyleVtbl, GetDashOffset) == offsetof(ID2D1StrokeStyleVtbl, GetDashOffset) ? 1 : -1];
typedef char pdk_off_ID2D1StrokeStyle_GetDashStyle[offsetof(PDK_ID2D1StrokeStyleVtbl, GetDashStyle) == offsetof(ID2D1StrokeStyleVtbl, GetDashStyle) ? 1 : -1];
typedef char pdk_off_ID2D1StrokeStyle_GetDashesCount[offsetof(PDK_ID2D1StrokeStyleVtbl, GetDashesCount) == offsetof(ID2D1StrokeStyleVtbl, GetDashesCount) ? 1 : -1];
typedef char pdk_off_ID2D1StrokeStyle_GetDashes[offsetof(PDK_ID2D1StrokeStyleVtbl, GetDashes) == offsetof(ID2D1StrokeStyleVtbl, GetDashes) ? 1 : -1];

/* ID2D1Geometry: 17 slots */
_Static_assert(sizeof(PDK_ID2D1GeometryVtbl) == sizeof(ID2D1GeometryVtbl), "ID2D1Geometry vtable size");
typedef char pdk_off_ID2D1Geometry_GetBounds[offsetof(PDK_ID2D1GeometryVtbl, GetBounds) == offsetof(ID2D1GeometryVtbl, GetBounds) ? 1 : -1];
typedef char pdk_off_ID2D1Geometry_GetWidenedBounds[offsetof(PDK_ID2D1GeometryVtbl, GetWidenedBounds) == offsetof(ID2D1GeometryVtbl, GetWidenedBounds) ? 1 : -1];
typedef char pdk_off_ID2D1Geometry_StrokeContainsPoint[offsetof(PDK_ID2D1GeometryVtbl, StrokeContainsPoint) == offsetof(ID2D1GeometryVtbl, StrokeContainsPoint) ? 1 : -1];
typedef char pdk_off_ID2D1Geometry_FillContainsPoint[offsetof(PDK_ID2D1GeometryVtbl, FillContainsPoint) == offsetof(ID2D1GeometryVtbl, FillContainsPoint) ? 1 : -1];
typedef char pdk_off_ID2D1Geometry_CompareWithGeometry[offsetof(PDK_ID2D1GeometryVtbl, CompareWithGeometry) == offsetof(ID2D1GeometryVtbl, CompareWithGeometry) ? 1 : -1];
typedef char pdk_off_ID2D1Geometry_Simplify[offsetof(PDK_ID2D1GeometryVtbl, Simplify) == offsetof(ID2D1GeometryVtbl, Simplify) ? 1 : -1];
typedef char pdk_off_ID2D1Geometry_Tessellate[offsetof(PDK_ID2D1GeometryVtbl, Tessellate) == offsetof(ID2D1GeometryVtbl, Tessellate) ? 1 : -1];
typedef char pdk_off_ID2D1Geometry_CombineWithGeometry[offsetof(PDK_ID2D1GeometryVtbl, CombineWithGeometry) == offsetof(ID2D1GeometryVtbl, CombineWithGeometry) ? 1 : -1];
typedef char pdk_off_ID2D1Geometry_Outline[offsetof(PDK_ID2D1GeometryVtbl, Outline) == offsetof(ID2D1GeometryVtbl, Outline) ? 1 : -1];
typedef char pdk_off_ID2D1Geometry_ComputeArea[offsetof(PDK_ID2D1GeometryVtbl, ComputeArea) == offsetof(ID2D1GeometryVtbl, ComputeArea) ? 1 : -1];
typedef char pdk_off_ID2D1Geometry_ComputeLength[offsetof(PDK_ID2D1GeometryVtbl, ComputeLength) == offsetof(ID2D1GeometryVtbl, ComputeLength) ? 1 : -1];
typedef char pdk_off_ID2D1Geometry_ComputePointAtLength[offsetof(PDK_ID2D1GeometryVtbl, ComputePointAtLength) == offsetof(ID2D1GeometryVtbl, ComputePointAtLength) ? 1 : -1];
typedef char pdk_off_ID2D1Geometry_Widen[offsetof(PDK_ID2D1GeometryVtbl, Widen) == offsetof(ID2D1GeometryVtbl, Widen) ? 1 : -1];

/* ID2D1PathGeometry: 21 slots */
_Static_assert(sizeof(PDK_ID2D1PathGeometryVtbl) == sizeof(ID2D1PathGeometryVtbl), "ID2D1PathGeometry vtable size");
typedef char pdk_off_ID2D1PathGeometry_Open[offsetof(PDK_ID2D1PathGeometryVtbl, Open) == offsetof(ID2D1PathGeometryVtbl, Open) ? 1 : -1];
typedef char pdk_off_ID2D1PathGeometry_Stream[offsetof(PDK_ID2D1PathGeometryVtbl, Stream) == offsetof(ID2D1PathGeometryVtbl, Stream) ? 1 : -1];
typedef char pdk_off_ID2D1PathGeometry_GetSegmentCount[offsetof(PDK_ID2D1PathGeometryVtbl, GetSegmentCount) == offsetof(ID2D1PathGeometryVtbl, GetSegmentCount) ? 1 : -1];
typedef char pdk_off_ID2D1PathGeometry_GetFigureCount[offsetof(PDK_ID2D1PathGeometryVtbl, GetFigureCount) == offsetof(ID2D1PathGeometryVtbl, GetFigureCount) ? 1 : -1];

/* ID2D1GeometrySink: 15 slots */
_Static_assert(sizeof(PDK_ID2D1GeometrySinkVtbl) == sizeof(ID2D1GeometrySinkVtbl), "ID2D1GeometrySink vtable size");
typedef char pdk_off_ID2D1GeometrySink_AddLine[offsetof(PDK_ID2D1GeometrySinkVtbl, AddLine) == offsetof(ID2D1GeometrySinkVtbl, AddLine) ? 1 : -1];
typedef char pdk_off_ID2D1GeometrySink_AddBezier[offsetof(PDK_ID2D1GeometrySinkVtbl, AddBezier) == offsetof(ID2D1GeometrySinkVtbl, AddBezier) ? 1 : -1];
typedef char pdk_off_ID2D1GeometrySink_AddQuadraticBezier[offsetof(PDK_ID2D1GeometrySinkVtbl, AddQuadraticBezier) == offsetof(ID2D1GeometrySinkVtbl, AddQuadraticBezier) ? 1 : -1];
typedef char pdk_off_ID2D1GeometrySink_AddQuadraticBeziers[offsetof(PDK_ID2D1GeometrySinkVtbl, AddQuadraticBeziers) == offsetof(ID2D1GeometrySinkVtbl, AddQuadraticBeziers) ? 1 : -1];
typedef char pdk_off_ID2D1GeometrySink_AddArc[offsetof(PDK_ID2D1GeometrySinkVtbl, AddArc) == offsetof(ID2D1GeometrySinkVtbl, AddArc) ? 1 : -1];

/* IDWriteFactory: 24 slots */
_Static_assert(sizeof(PDK_IDWriteFactoryVtbl) == sizeof(IDWriteFactoryVtbl), "IDWriteFactory vtable size");
typedef char pdk_off_IDWriteFactory_QueryInterface[offsetof(PDK_IDWriteFactoryVtbl, QueryInterface) == offsetof(IDWriteFactoryVtbl, QueryInterface) ? 1 : -1];
typedef char pdk_off_IDWriteFactory_AddRef[offsetof(PDK_IDWriteFactoryVtbl, AddRef) == offsetof(IDWriteFactoryVtbl, AddRef) ? 1 : -1];
typedef char pdk_off_IDWriteFactory_Release[offsetof(PDK_IDWriteFactoryVtbl, Release) == offsetof(IDWriteFactoryVtbl, Release) ? 1 : -1];
typedef char pdk_off_IDWriteFactory_GetSystemFontCollection[offsetof(PDK_IDWriteFactoryVtbl, GetSystemFontCollection) == offsetof(IDWriteFactoryVtbl, GetSystemFontCollection) ? 1 : -1];
typedef char pdk_off_IDWriteFactory_CreateCustomFontCollection[offsetof(PDK_IDWriteFactoryVtbl, CreateCustomFontCollection) == offsetof(IDWriteFactoryVtbl, CreateCustomFontCollection) ? 1 : -1];
typedef char pdk_off_IDWriteFactory_RegisterFontCollectionLoader[offsetof(PDK_IDWriteFactoryVtbl, RegisterFontCollectionLoader) == offsetof(IDWriteFactoryVtbl, RegisterFontCollectionLoader) ? 1 : -1];
typedef char pdk_off_IDWriteFactory_UnregisterFontCollectionLoader[offsetof(PDK_IDWriteFactoryVtbl, UnregisterFontCollectionLoader) == offsetof(IDWriteFactoryVtbl, UnregisterFontCollectionLoader) ? 1 : -1];
typedef char pdk_off_IDWriteFactory_CreateFontFileReference[offsetof(PDK_IDWriteFactoryVtbl, CreateFontFileReference) == offsetof(IDWriteFactoryVtbl, CreateFontFileReference) ? 1 : -1];
typedef char pdk_off_IDWriteFactory_CreateCustomFontFileReference[offsetof(PDK_IDWriteFactoryVtbl, CreateCustomFontFileReference) == offsetof(IDWriteFactoryVtbl, CreateCustomFontFileReference) ? 1 : -1];
typedef char pdk_off_IDWriteFactory_CreateFontFace[offsetof(PDK_IDWriteFactoryVtbl, CreateFontFace) == offsetof(IDWriteFactoryVtbl, CreateFontFace) ? 1 : -1];
typedef char pdk_off_IDWriteFactory_CreateRenderingParams[offsetof(PDK_IDWriteFactoryVtbl, CreateRenderingParams) == offsetof(IDWriteFactoryVtbl, CreateRenderingParams) ? 1 : -1];
typedef char pdk_off_IDWriteFactory_CreateMonitorRenderingParams[offsetof(PDK_IDWriteFactoryVtbl, CreateMonitorRenderingParams) == offsetof(IDWriteFactoryVtbl, CreateMonitorRenderingParams) ? 1 : -1];
typedef char pdk_off_IDWriteFactory_CreateCustomRenderingParams[offsetof(PDK_IDWriteFactoryVtbl, CreateCustomRenderingParams) == offsetof(IDWriteFactoryVtbl, CreateCustomRenderingParams) ? 1 : -1];
typedef char pdk_off_IDWriteFactory_RegisterFontFileLoader[offsetof(PDK_IDWriteFactoryVtbl, RegisterFontFileLoader) == offsetof(IDWriteFactoryVtbl, RegisterFontFileLoader) ? 1 : -1];
typedef char pdk_off_IDWriteFactory_UnregisterFontFileLoader[offsetof(PDK_IDWriteFactoryVtbl, UnregisterFontFileLoader) == offsetof(IDWriteFactoryVtbl, UnregisterFontFileLoader) ? 1 : -1];
typedef char pdk_off_IDWriteFactory_CreateTextFormat[offsetof(PDK_IDWriteFactoryVtbl, CreateTextFormat) == offsetof(IDWriteFactoryVtbl, CreateTextFormat) ? 1 : -1];
typedef char pdk_off_IDWriteFactory_CreateTypography[offsetof(PDK_IDWriteFactoryVtbl, CreateTypography) == offsetof(IDWriteFactoryVtbl, CreateTypography) ? 1 : -1];
typedef char pdk_off_IDWriteFactory_GetGdiInterop[offsetof(PDK_IDWriteFactoryVtbl, GetGdiInterop) == offsetof(IDWriteFactoryVtbl, GetGdiInterop) ? 1 : -1];
typedef char pdk_off_IDWriteFactory_CreateTextLayout[offsetof(PDK_IDWriteFactoryVtbl, CreateTextLayout) == offsetof(IDWriteFactoryVtbl, CreateTextLayout) ? 1 : -1];
typedef char pdk_off_IDWriteFactory_CreateGdiCompatibleTextLayout[offsetof(PDK_IDWriteFactoryVtbl, CreateGdiCompatibleTextLayout) == offsetof(IDWriteFactoryVtbl, CreateGdiCompatibleTextLayout) ? 1 : -1];
typedef char pdk_off_IDWriteFactory_CreateEllipsisTrimmingSign[offsetof(PDK_IDWriteFactoryVtbl, CreateEllipsisTrimmingSign) == offsetof(IDWriteFactoryVtbl, CreateEllipsisTrimmingSign) ? 1 : -1];
typedef char pdk_off_IDWriteFactory_CreateTextAnalyzer[offsetof(PDK_IDWriteFactoryVtbl, CreateTextAnalyzer) == offsetof(IDWriteFactoryVtbl, CreateTextAnalyzer) ? 1 : -1];
typedef char pdk_off_IDWriteFactory_CreateNumberSubstitution[offsetof(PDK_IDWriteFactoryVtbl, CreateNumberSubstitution) == offsetof(IDWriteFactoryVtbl, CreateNumberSubstitution) ? 1 : -1];
typedef char pdk_off_IDWriteFactory_CreateGlyphRunAnalysis[offsetof(PDK_IDWriteFactoryVtbl, CreateGlyphRunAnalysis) == offsetof(IDWriteFactoryVtbl, CreateGlyphRunAnalysis) ? 1 : -1];

/* IDWriteTextFormat: 28 slots */
_Static_assert(sizeof(PDK_IDWriteTextFormatVtbl) == sizeof(IDWriteTextFormatVtbl), "IDWriteTextFormat vtable size");
typedef char pdk_off_IDWriteTextFormat_QueryInterface[offsetof(PDK_IDWriteTextFormatVtbl, QueryInterface) == offsetof(IDWriteTextFormatVtbl, QueryInterface) ? 1 : -1];
typedef char pdk_off_IDWriteTextFormat_AddRef[offsetof(PDK_IDWriteTextFormatVtbl, AddRef) == offsetof(IDWriteTextFormatVtbl, AddRef) ? 1 : -1];
typedef char pdk_off_IDWriteTextFormat_Release[offsetof(PDK_IDWriteTextFormatVtbl, Release) == offsetof(IDWriteTextFormatVtbl, Release) ? 1 : -1];
typedef char pdk_off_IDWriteTextFormat_SetTextAlignment[offsetof(PDK_IDWriteTextFormatVtbl, SetTextAlignment) == offsetof(IDWriteTextFormatVtbl, SetTextAlignment) ? 1 : -1];
typedef char pdk_off_IDWriteTextFormat_SetParagraphAlignment[offsetof(PDK_IDWriteTextFormatVtbl, SetParagraphAlignment) == offsetof(IDWriteTextFormatVtbl, SetParagraphAlignment) ? 1 : -1];
typedef char pdk_off_IDWriteTextFormat_SetWordWrapping[offsetof(PDK_IDWriteTextFormatVtbl, SetWordWrapping) == offsetof(IDWriteTextFormatVtbl, SetWordWrapping) ? 1 : -1];
typedef char pdk_off_IDWriteTextFormat_SetReadingDirection[offsetof(PDK_IDWriteTextFormatVtbl, SetReadingDirection) == offsetof(IDWriteTextFormatVtbl, SetReadingDirection) ? 1 : -1];
typedef char pdk_off_IDWriteTextFormat_SetFlowDirection[offsetof(PDK_IDWriteTextFormatVtbl, SetFlowDirection) == offsetof(IDWriteTextFormatVtbl, SetFlowDirection) ? 1 : -1];
typedef char pdk_off_IDWriteTextFormat_SetIncrementalTabStop[offsetof(PDK_IDWriteTextFormatVtbl, SetIncrementalTabStop) == offsetof(IDWriteTextFormatVtbl, SetIncrementalTabStop) ? 1 : -1];
typedef char pdk_off_IDWriteTextFormat_SetTrimming[offsetof(PDK_IDWriteTextFormatVtbl, SetTrimming) == offsetof(IDWriteTextFormatVtbl, SetTrimming) ? 1 : -1];
typedef char pdk_off_IDWriteTextFormat_SetLineSpacing[offsetof(PDK_IDWriteTextFormatVtbl, SetLineSpacing) == offsetof(IDWriteTextFormatVtbl, SetLineSpacing) ? 1 : -1];
typedef char pdk_off_IDWriteTextFormat_GetTextAlignment[offsetof(PDK_IDWriteTextFormatVtbl, GetTextAlignment) == offsetof(IDWriteTextFormatVtbl, GetTextAlignment) ? 1 : -1];
typedef char pdk_off_IDWriteTextFormat_GetParagraphAlignment[offsetof(PDK_IDWriteTextFormatVtbl, GetParagraphAlignment) == offsetof(IDWriteTextFormatVtbl, GetParagraphAlignment) ? 1 : -1];
typedef char pdk_off_IDWriteTextFormat_GetWordWrapping[offsetof(PDK_IDWriteTextFormatVtbl, GetWordWrapping) == offsetof(IDWriteTextFormatVtbl, GetWordWrapping) ? 1 : -1];
typedef char pdk_off_IDWriteTextFormat_GetReadingDirection[offsetof(PDK_IDWriteTextFormatVtbl, GetReadingDirection) == offsetof(IDWriteTextFormatVtbl, GetReadingDirection) ? 1 : -1];
typedef char pdk_off_IDWriteTextFormat_GetFlowDirection[offsetof(PDK_IDWriteTextFormatVtbl, GetFlowDirection) == offsetof(IDWriteTextFormatVtbl, GetFlowDirection) ? 1 : -1];
typedef char pdk_off_IDWriteTextFormat_GetIncrementalTabStop[offsetof(PDK_IDWriteTextFormatVtbl, GetIncrementalTabStop) == offsetof(IDWriteTextFormatVtbl, GetIncrementalTabStop) ? 1 : -1];
typedef char pdk_off_IDWriteTextFormat_GetTrimming[offsetof(PDK_IDWriteTextFormatVtbl, GetTrimming) == offsetof(IDWriteTextFormatVtbl, GetTrimming) ? 1 : -1];
typedef char pdk_off_IDWriteTextFormat_GetLineSpacing[offsetof(PDK_IDWriteTextFormatVtbl, GetLineSpacing) == offsetof(IDWriteTextFormatVtbl, GetLineSpacing) ? 1 : -1];
typedef char pdk_off_IDWriteTextFormat_GetFontCollection[offsetof(PDK_IDWriteTextFormatVtbl, GetFontCollection) == offsetof(IDWriteTextFormatVtbl, GetFontCollection) ? 1 : -1];
typedef char pdk_off_IDWriteTextFormat_GetFontFamilyNameLength[offsetof(PDK_IDWriteTextFormatVtbl, GetFontFamilyNameLength) == offsetof(IDWriteTextFormatVtbl, GetFontFamilyNameLength) ? 1 : -1];
typedef char pdk_off_IDWriteTextFormat_GetFontFamilyName[offsetof(PDK_IDWriteTextFormatVtbl, GetFontFamilyName) == offsetof(IDWriteTextFormatVtbl, GetFontFamilyName) ? 1 : -1];
typedef char pdk_off_IDWriteTextFormat_GetFontWeight[offsetof(PDK_IDWriteTextFormatVtbl, GetFontWeight) == offsetof(IDWriteTextFormatVtbl, GetFontWeight) ? 1 : -1];
typedef char pdk_off_IDWriteTextFormat_GetFontStyle[offsetof(PDK_IDWriteTextFormatVtbl, GetFontStyle) == offsetof(IDWriteTextFormatVtbl, GetFontStyle) ? 1 : -1];
typedef char pdk_off_IDWriteTextFormat_GetFontStretch[offsetof(PDK_IDWriteTextFormatVtbl, GetFontStretch) == offsetof(IDWriteTextFormatVtbl, GetFontStretch) ? 1 : -1];
typedef char pdk_off_IDWriteTextFormat_GetFontSize[offsetof(PDK_IDWriteTextFormatVtbl, GetFontSize) == offsetof(IDWriteTextFormatVtbl, GetFontSize) ? 1 : -1];
typedef char pdk_off_IDWriteTextFormat_GetLocaleNameLength[offsetof(PDK_IDWriteTextFormatVtbl, GetLocaleNameLength) == offsetof(IDWriteTextFormatVtbl, GetLocaleNameLength) ? 1 : -1];
typedef char pdk_off_IDWriteTextFormat_GetLocaleName[offsetof(PDK_IDWriteTextFormatVtbl, GetLocaleName) == offsetof(IDWriteTextFormatVtbl, GetLocaleName) ? 1 : -1];

/* IDWriteTextLayout: 67 slots */
_Static_assert(sizeof(PDK_IDWriteTextLayoutVtbl) == sizeof(IDWriteTextLayoutVtbl), "IDWriteTextLayout vtable size");
typedef char pdk_off_IDWriteTextLayout_QueryInterface[offsetof(PDK_IDWriteTextLayoutVtbl, QueryInterface) == offsetof(IDWriteTextLayoutVtbl, QueryInterface) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_AddRef[offsetof(PDK_IDWriteTextLayoutVtbl, AddRef) == offsetof(IDWriteTextLayoutVtbl, AddRef) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_Release[offsetof(PDK_IDWriteTextLayoutVtbl, Release) == offsetof(IDWriteTextLayoutVtbl, Release) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_SetTextAlignment[offsetof(PDK_IDWriteTextLayoutVtbl, SetTextAlignment) == offsetof(IDWriteTextLayoutVtbl, SetTextAlignment) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_SetParagraphAlignment[offsetof(PDK_IDWriteTextLayoutVtbl, SetParagraphAlignment) == offsetof(IDWriteTextLayoutVtbl, SetParagraphAlignment) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_SetWordWrapping[offsetof(PDK_IDWriteTextLayoutVtbl, SetWordWrapping) == offsetof(IDWriteTextLayoutVtbl, SetWordWrapping) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_SetReadingDirection[offsetof(PDK_IDWriteTextLayoutVtbl, SetReadingDirection) == offsetof(IDWriteTextLayoutVtbl, SetReadingDirection) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_SetFlowDirection[offsetof(PDK_IDWriteTextLayoutVtbl, SetFlowDirection) == offsetof(IDWriteTextLayoutVtbl, SetFlowDirection) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_SetIncrementalTabStop[offsetof(PDK_IDWriteTextLayoutVtbl, SetIncrementalTabStop) == offsetof(IDWriteTextLayoutVtbl, SetIncrementalTabStop) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_SetTrimming[offsetof(PDK_IDWriteTextLayoutVtbl, SetTrimming) == offsetof(IDWriteTextLayoutVtbl, SetTrimming) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_SetLineSpacing[offsetof(PDK_IDWriteTextLayoutVtbl, SetLineSpacing) == offsetof(IDWriteTextLayoutVtbl, SetLineSpacing) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_GetTextAlignment[offsetof(PDK_IDWriteTextLayoutVtbl, GetTextAlignment) == offsetof(IDWriteTextLayoutVtbl, GetTextAlignment) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_GetParagraphAlignment[offsetof(PDK_IDWriteTextLayoutVtbl, GetParagraphAlignment) == offsetof(IDWriteTextLayoutVtbl, GetParagraphAlignment) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_GetWordWrapping[offsetof(PDK_IDWriteTextLayoutVtbl, GetWordWrapping) == offsetof(IDWriteTextLayoutVtbl, GetWordWrapping) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_GetReadingDirection[offsetof(PDK_IDWriteTextLayoutVtbl, GetReadingDirection) == offsetof(IDWriteTextLayoutVtbl, GetReadingDirection) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_GetFlowDirection[offsetof(PDK_IDWriteTextLayoutVtbl, GetFlowDirection) == offsetof(IDWriteTextLayoutVtbl, GetFlowDirection) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_GetIncrementalTabStop[offsetof(PDK_IDWriteTextLayoutVtbl, GetIncrementalTabStop) == offsetof(IDWriteTextLayoutVtbl, GetIncrementalTabStop) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_GetTrimming[offsetof(PDK_IDWriteTextLayoutVtbl, GetTrimming) == offsetof(IDWriteTextLayoutVtbl, GetTrimming) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_GetLineSpacing[offsetof(PDK_IDWriteTextLayoutVtbl, GetLineSpacing) == offsetof(IDWriteTextLayoutVtbl, GetLineSpacing) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_GetFontCollection[offsetof(PDK_IDWriteTextLayoutVtbl, GetFontCollection) == offsetof(IDWriteTextLayoutVtbl, GetFontCollection) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_GetFontFamilyNameLength[offsetof(PDK_IDWriteTextLayoutVtbl, GetFontFamilyNameLength) == offsetof(IDWriteTextLayoutVtbl, GetFontFamilyNameLength) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_GetFontFamilyName[offsetof(PDK_IDWriteTextLayoutVtbl, GetFontFamilyName) == offsetof(IDWriteTextLayoutVtbl, GetFontFamilyName) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_GetFontWeight[offsetof(PDK_IDWriteTextLayoutVtbl, GetFontWeight) == offsetof(IDWriteTextLayoutVtbl, GetFontWeight) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_GetFontStyle[offsetof(PDK_IDWriteTextLayoutVtbl, GetFontStyle) == offsetof(IDWriteTextLayoutVtbl, GetFontStyle) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_GetFontStretch[offsetof(PDK_IDWriteTextLayoutVtbl, GetFontStretch) == offsetof(IDWriteTextLayoutVtbl, GetFontStretch) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_GetFontSize[offsetof(PDK_IDWriteTextLayoutVtbl, GetFontSize) == offsetof(IDWriteTextLayoutVtbl, GetFontSize) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_GetLocaleNameLength[offsetof(PDK_IDWriteTextLayoutVtbl, GetLocaleNameLength) == offsetof(IDWriteTextLayoutVtbl, GetLocaleNameLength) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_GetLocaleName[offsetof(PDK_IDWriteTextLayoutVtbl, GetLocaleName) == offsetof(IDWriteTextLayoutVtbl, GetLocaleName) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_SetMaxWidth[offsetof(PDK_IDWriteTextLayoutVtbl, SetMaxWidth) == offsetof(IDWriteTextLayoutVtbl, SetMaxWidth) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_SetMaxHeight[offsetof(PDK_IDWriteTextLayoutVtbl, SetMaxHeight) == offsetof(IDWriteTextLayoutVtbl, SetMaxHeight) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_SetFontCollection[offsetof(PDK_IDWriteTextLayoutVtbl, SetFontCollection) == offsetof(IDWriteTextLayoutVtbl, SetFontCollection) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_SetFontFamilyName[offsetof(PDK_IDWriteTextLayoutVtbl, SetFontFamilyName) == offsetof(IDWriteTextLayoutVtbl, SetFontFamilyName) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_SetFontWeight[offsetof(PDK_IDWriteTextLayoutVtbl, SetFontWeight) == offsetof(IDWriteTextLayoutVtbl, SetFontWeight) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_SetFontStyle[offsetof(PDK_IDWriteTextLayoutVtbl, SetFontStyle) == offsetof(IDWriteTextLayoutVtbl, SetFontStyle) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_SetFontStretch[offsetof(PDK_IDWriteTextLayoutVtbl, SetFontStretch) == offsetof(IDWriteTextLayoutVtbl, SetFontStretch) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_SetFontSize[offsetof(PDK_IDWriteTextLayoutVtbl, SetFontSize) == offsetof(IDWriteTextLayoutVtbl, SetFontSize) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_SetUnderline[offsetof(PDK_IDWriteTextLayoutVtbl, SetUnderline) == offsetof(IDWriteTextLayoutVtbl, SetUnderline) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_SetStrikethrough[offsetof(PDK_IDWriteTextLayoutVtbl, SetStrikethrough) == offsetof(IDWriteTextLayoutVtbl, SetStrikethrough) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_SetDrawingEffect[offsetof(PDK_IDWriteTextLayoutVtbl, SetDrawingEffect) == offsetof(IDWriteTextLayoutVtbl, SetDrawingEffect) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_SetInlineObject[offsetof(PDK_IDWriteTextLayoutVtbl, SetInlineObject) == offsetof(IDWriteTextLayoutVtbl, SetInlineObject) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_SetTypography[offsetof(PDK_IDWriteTextLayoutVtbl, SetTypography) == offsetof(IDWriteTextLayoutVtbl, SetTypography) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_SetLocaleName[offsetof(PDK_IDWriteTextLayoutVtbl, SetLocaleName) == offsetof(IDWriteTextLayoutVtbl, SetLocaleName) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_GetMaxWidth[offsetof(PDK_IDWriteTextLayoutVtbl, GetMaxWidth) == offsetof(IDWriteTextLayoutVtbl, GetMaxWidth) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_GetMaxHeight[offsetof(PDK_IDWriteTextLayoutVtbl, GetMaxHeight) == offsetof(IDWriteTextLayoutVtbl, GetMaxHeight) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_IDWriteTextLayout_GetFontCollection[offsetof(PDK_IDWriteTextLayoutVtbl, IDWriteTextLayout_GetFontCollection) == offsetof(IDWriteTextLayoutVtbl, IDWriteTextLayout_GetFontCollection) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_IDWriteTextLayout_GetFontFamilyNameLength[offsetof(PDK_IDWriteTextLayoutVtbl, IDWriteTextLayout_GetFontFamilyNameLength) == offsetof(IDWriteTextLayoutVtbl, IDWriteTextLayout_GetFontFamilyNameLength) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_IDWriteTextLayout_GetFontFamilyName[offsetof(PDK_IDWriteTextLayoutVtbl, IDWriteTextLayout_GetFontFamilyName) == offsetof(IDWriteTextLayoutVtbl, IDWriteTextLayout_GetFontFamilyName) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_IDWriteTextLayout_GetFontWeight[offsetof(PDK_IDWriteTextLayoutVtbl, IDWriteTextLayout_GetFontWeight) == offsetof(IDWriteTextLayoutVtbl, IDWriteTextLayout_GetFontWeight) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_IDWriteTextLayout_GetFontStyle[offsetof(PDK_IDWriteTextLayoutVtbl, IDWriteTextLayout_GetFontStyle) == offsetof(IDWriteTextLayoutVtbl, IDWriteTextLayout_GetFontStyle) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_IDWriteTextLayout_GetFontStretch[offsetof(PDK_IDWriteTextLayoutVtbl, IDWriteTextLayout_GetFontStretch) == offsetof(IDWriteTextLayoutVtbl, IDWriteTextLayout_GetFontStretch) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_IDWriteTextLayout_GetFontSize[offsetof(PDK_IDWriteTextLayoutVtbl, IDWriteTextLayout_GetFontSize) == offsetof(IDWriteTextLayoutVtbl, IDWriteTextLayout_GetFontSize) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_GetUnderline[offsetof(PDK_IDWriteTextLayoutVtbl, GetUnderline) == offsetof(IDWriteTextLayoutVtbl, GetUnderline) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_GetStrikethrough[offsetof(PDK_IDWriteTextLayoutVtbl, GetStrikethrough) == offsetof(IDWriteTextLayoutVtbl, GetStrikethrough) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_GetDrawingEffect[offsetof(PDK_IDWriteTextLayoutVtbl, GetDrawingEffect) == offsetof(IDWriteTextLayoutVtbl, GetDrawingEffect) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_GetInlineObject[offsetof(PDK_IDWriteTextLayoutVtbl, GetInlineObject) == offsetof(IDWriteTextLayoutVtbl, GetInlineObject) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_GetTypography[offsetof(PDK_IDWriteTextLayoutVtbl, GetTypography) == offsetof(IDWriteTextLayoutVtbl, GetTypography) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_IDWriteTextLayout_GetLocaleNameLength[offsetof(PDK_IDWriteTextLayoutVtbl, IDWriteTextLayout_GetLocaleNameLength) == offsetof(IDWriteTextLayoutVtbl, IDWriteTextLayout_GetLocaleNameLength) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_IDWriteTextLayout_GetLocaleName[offsetof(PDK_IDWriteTextLayoutVtbl, IDWriteTextLayout_GetLocaleName) == offsetof(IDWriteTextLayoutVtbl, IDWriteTextLayout_GetLocaleName) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_Draw[offsetof(PDK_IDWriteTextLayoutVtbl, Draw) == offsetof(IDWriteTextLayoutVtbl, Draw) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_GetLineMetrics[offsetof(PDK_IDWriteTextLayoutVtbl, GetLineMetrics) == offsetof(IDWriteTextLayoutVtbl, GetLineMetrics) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_GetMetrics[offsetof(PDK_IDWriteTextLayoutVtbl, GetMetrics) == offsetof(IDWriteTextLayoutVtbl, GetMetrics) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_GetOverhangMetrics[offsetof(PDK_IDWriteTextLayoutVtbl, GetOverhangMetrics) == offsetof(IDWriteTextLayoutVtbl, GetOverhangMetrics) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_GetClusterMetrics[offsetof(PDK_IDWriteTextLayoutVtbl, GetClusterMetrics) == offsetof(IDWriteTextLayoutVtbl, GetClusterMetrics) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_DetermineMinWidth[offsetof(PDK_IDWriteTextLayoutVtbl, DetermineMinWidth) == offsetof(IDWriteTextLayoutVtbl, DetermineMinWidth) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_HitTestPoint[offsetof(PDK_IDWriteTextLayoutVtbl, HitTestPoint) == offsetof(IDWriteTextLayoutVtbl, HitTestPoint) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_HitTestTextPosition[offsetof(PDK_IDWriteTextLayoutVtbl, HitTestTextPosition) == offsetof(IDWriteTextLayoutVtbl, HitTestTextPosition) ? 1 : -1];
typedef char pdk_off_IDWriteTextLayout_HitTestTextRange[offsetof(PDK_IDWriteTextLayoutVtbl, HitTestTextRange) == offsetof(IDWriteTextLayoutVtbl, HitTestTextRange) ? 1 : -1];

/* IDWriteInlineObject: 7 slots */
_Static_assert(sizeof(PDK_IDWriteInlineObjectVtbl) == sizeof(IDWriteInlineObjectVtbl), "IDWriteInlineObject vtable size");
typedef char pdk_off_IDWriteInlineObject_QueryInterface[offsetof(PDK_IDWriteInlineObjectVtbl, QueryInterface) == offsetof(IDWriteInlineObjectVtbl, QueryInterface) ? 1 : -1];
typedef char pdk_off_IDWriteInlineObject_AddRef[offsetof(PDK_IDWriteInlineObjectVtbl, AddRef) == offsetof(IDWriteInlineObjectVtbl, AddRef) ? 1 : -1];
typedef char pdk_off_IDWriteInlineObject_Release[offsetof(PDK_IDWriteInlineObjectVtbl, Release) == offsetof(IDWriteInlineObjectVtbl, Release) ? 1 : -1];
typedef char pdk_off_IDWriteInlineObject_Draw[offsetof(PDK_IDWriteInlineObjectVtbl, Draw) == offsetof(IDWriteInlineObjectVtbl, Draw) ? 1 : -1];
typedef char pdk_off_IDWriteInlineObject_GetMetrics[offsetof(PDK_IDWriteInlineObjectVtbl, GetMetrics) == offsetof(IDWriteInlineObjectVtbl, GetMetrics) ? 1 : -1];
typedef char pdk_off_IDWriteInlineObject_GetOverhangMetrics[offsetof(PDK_IDWriteInlineObjectVtbl, GetOverhangMetrics) == offsetof(IDWriteInlineObjectVtbl, GetOverhangMetrics) ? 1 : -1];
typedef char pdk_off_IDWriteInlineObject_GetBreakConditions[offsetof(PDK_IDWriteInlineObjectVtbl, GetBreakConditions) == offsetof(IDWriteInlineObjectVtbl, GetBreakConditions) ? 1 : -1];
