/* AUTO-GENERATED by tools/gen_com_shim.py -- do not edit by hand.
 * Regenerate with: python tools/gen_com_shim.py
 * Source of truth: MinGW-w64 C-mode SDK headers; layout is verified at
 * compile time by tests/shim_layout (MinGW) -- see plan.md 3.3.
 */
#ifndef PDK_SRC_GRAPHICS_D2D_C_H
#define PDK_SRC_GRAPHICS_D2D_C_H
/* Flat PDK vtables for Direct2D.  D2D1_* structs and enums come from
 * the platform <d2d1.h>, which both MSVC C mode and MinGW C mode parse.
 * Method order/size is asserted against the SDK in tests/shim_layout. */
#include "graphics/Com.h"
#include <d2d1.h>
#include "graphics/iids_gen.h"
#include "graphics/dwrite_c.h"

typedef struct PDK_ID2D1Factory PDK_ID2D1Factory;
typedef struct PDK_ID2D1FactoryVtbl PDK_ID2D1FactoryVtbl;
typedef struct PDK_ID2D1Resource PDK_ID2D1Resource;
typedef struct PDK_ID2D1ResourceVtbl PDK_ID2D1ResourceVtbl;
typedef struct PDK_ID2D1RenderTarget PDK_ID2D1RenderTarget;
typedef struct PDK_ID2D1RenderTargetVtbl PDK_ID2D1RenderTargetVtbl;
typedef struct PDK_ID2D1HwndRenderTarget PDK_ID2D1HwndRenderTarget;
typedef struct PDK_ID2D1HwndRenderTargetVtbl PDK_ID2D1HwndRenderTargetVtbl;
typedef struct PDK_ID2D1Brush PDK_ID2D1Brush;
typedef struct PDK_ID2D1BrushVtbl PDK_ID2D1BrushVtbl;
typedef struct PDK_ID2D1SolidColorBrush PDK_ID2D1SolidColorBrush;
typedef struct PDK_ID2D1SolidColorBrushVtbl PDK_ID2D1SolidColorBrushVtbl;
typedef struct PDK_ID2D1LinearGradientBrush PDK_ID2D1LinearGradientBrush;
typedef struct PDK_ID2D1LinearGradientBrushVtbl PDK_ID2D1LinearGradientBrushVtbl;
typedef struct PDK_ID2D1RadialGradientBrush PDK_ID2D1RadialGradientBrush;
typedef struct PDK_ID2D1RadialGradientBrushVtbl PDK_ID2D1RadialGradientBrushVtbl;
typedef struct PDK_ID2D1BitmapBrush PDK_ID2D1BitmapBrush;
typedef struct PDK_ID2D1BitmapBrushVtbl PDK_ID2D1BitmapBrushVtbl;
typedef struct PDK_ID2D1Image PDK_ID2D1Image;
typedef struct PDK_ID2D1ImageVtbl PDK_ID2D1ImageVtbl;
typedef struct PDK_ID2D1Bitmap PDK_ID2D1Bitmap;
typedef struct PDK_ID2D1BitmapVtbl PDK_ID2D1BitmapVtbl;
typedef struct PDK_ID2D1GradientStopCollection PDK_ID2D1GradientStopCollection;
typedef struct PDK_ID2D1GradientStopCollectionVtbl PDK_ID2D1GradientStopCollectionVtbl;
typedef struct PDK_ID2D1StrokeStyle PDK_ID2D1StrokeStyle;
typedef struct PDK_ID2D1StrokeStyleVtbl PDK_ID2D1StrokeStyleVtbl;
typedef struct PDK_ID2D1Geometry PDK_ID2D1Geometry;
typedef struct PDK_ID2D1GeometryVtbl PDK_ID2D1GeometryVtbl;
typedef struct PDK_ID2D1PathGeometry PDK_ID2D1PathGeometry;
typedef struct PDK_ID2D1PathGeometryVtbl PDK_ID2D1PathGeometryVtbl;
typedef struct PDK_ID2D1GeometrySink PDK_ID2D1GeometrySink;
typedef struct PDK_ID2D1GeometrySinkVtbl PDK_ID2D1GeometrySinkVtbl;

struct PDK_ID2D1Factory { const PDK_ID2D1FactoryVtbl *lpVtbl; };
struct PDK_ID2D1Resource { const PDK_ID2D1ResourceVtbl *lpVtbl; };
struct PDK_ID2D1RenderTarget { const PDK_ID2D1RenderTargetVtbl *lpVtbl; };
struct PDK_ID2D1HwndRenderTarget { const PDK_ID2D1HwndRenderTargetVtbl *lpVtbl; };
struct PDK_ID2D1Brush { const PDK_ID2D1BrushVtbl *lpVtbl; };
struct PDK_ID2D1SolidColorBrush { const PDK_ID2D1SolidColorBrushVtbl *lpVtbl; };
struct PDK_ID2D1LinearGradientBrush { const PDK_ID2D1LinearGradientBrushVtbl *lpVtbl; };
struct PDK_ID2D1RadialGradientBrush { const PDK_ID2D1RadialGradientBrushVtbl *lpVtbl; };
struct PDK_ID2D1BitmapBrush { const PDK_ID2D1BitmapBrushVtbl *lpVtbl; };
struct PDK_ID2D1Image { const PDK_ID2D1ImageVtbl *lpVtbl; };
struct PDK_ID2D1Bitmap { const PDK_ID2D1BitmapVtbl *lpVtbl; };
struct PDK_ID2D1GradientStopCollection { const PDK_ID2D1GradientStopCollectionVtbl *lpVtbl; };
struct PDK_ID2D1StrokeStyle { const PDK_ID2D1StrokeStyleVtbl *lpVtbl; };
struct PDK_ID2D1Geometry { const PDK_ID2D1GeometryVtbl *lpVtbl; };
struct PDK_ID2D1PathGeometry { const PDK_ID2D1PathGeometryVtbl *lpVtbl; };
struct PDK_ID2D1GeometrySink { const PDK_ID2D1GeometrySinkVtbl *lpVtbl; };

struct PDK_ID2D1FactoryVtbl {
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(void *This, REFIID riid, void **ppvObject);
    ULONG (STDMETHODCALLTYPE *AddRef)(void *This);
    ULONG (STDMETHODCALLTYPE *Release)(void *This);
    HRESULT (STDMETHODCALLTYPE *ReloadSystemMetrics)(PDK_ID2D1Factory *This);
    void (STDMETHODCALLTYPE *GetDesktopDpi)(PDK_ID2D1Factory *This, FLOAT *dpiX, FLOAT *dpiY);
    HRESULT (STDMETHODCALLTYPE *CreateRectangleGeometry)(PDK_ID2D1Factory *This, const D2D1_RECT_F *rectangle, void **rectangleGeometry);
    HRESULT (STDMETHODCALLTYPE *CreateRoundedRectangleGeometry)(PDK_ID2D1Factory *This, const D2D1_ROUNDED_RECT *roundedRectangle, void **roundedRectangleGeometry);
    HRESULT (STDMETHODCALLTYPE *CreateEllipseGeometry)(PDK_ID2D1Factory *This, const D2D1_ELLIPSE *ellipse, void **ellipseGeometry);
    HRESULT (STDMETHODCALLTYPE *CreateGeometryGroup)(PDK_ID2D1Factory *This, D2D1_FILL_MODE fillMode, PDK_ID2D1Geometry **geometries, UINT geometriesCount, void **geometryGroup);
    HRESULT (STDMETHODCALLTYPE *CreateTransformedGeometry)(PDK_ID2D1Factory *This, PDK_ID2D1Geometry *sourceGeometry, const D2D1_MATRIX_3X2_F *transform, void **transformedGeometry);
    HRESULT (STDMETHODCALLTYPE *CreatePathGeometry)(PDK_ID2D1Factory *This, PDK_ID2D1PathGeometry **pathGeometry);
    HRESULT (STDMETHODCALLTYPE *CreateStrokeStyle)(PDK_ID2D1Factory *This, const D2D1_STROKE_STYLE_PROPERTIES *strokeStyleProperties, const FLOAT *dashes, UINT dashesCount, PDK_ID2D1StrokeStyle **strokeStyle);
    HRESULT (STDMETHODCALLTYPE *CreateDrawingStateBlock)(PDK_ID2D1Factory *This, const D2D1_DRAWING_STATE_DESCRIPTION *drawingStateDescription, void *textRenderingParams, void **drawingStateBlock);
    HRESULT (STDMETHODCALLTYPE *CreateWicBitmapRenderTarget)(PDK_ID2D1Factory *This, void *target, const D2D1_RENDER_TARGET_PROPERTIES *renderTargetProperties, PDK_ID2D1RenderTarget **renderTarget);
    HRESULT (STDMETHODCALLTYPE *CreateHwndRenderTarget)(PDK_ID2D1Factory *This, const D2D1_RENDER_TARGET_PROPERTIES *renderTargetProperties, const D2D1_HWND_RENDER_TARGET_PROPERTIES *hwndRenderTargetProperties, PDK_ID2D1HwndRenderTarget **hwndRenderTarget);
    HRESULT (STDMETHODCALLTYPE *CreateDxgiSurfaceRenderTarget)(PDK_ID2D1Factory *This, void *dxgiSurface, const D2D1_RENDER_TARGET_PROPERTIES *renderTargetProperties, PDK_ID2D1RenderTarget **renderTarget);
    HRESULT (STDMETHODCALLTYPE *CreateDCRenderTarget)(PDK_ID2D1Factory *This, const D2D1_RENDER_TARGET_PROPERTIES *renderTargetProperties, void **dcRenderTarget);
};

struct PDK_ID2D1ResourceVtbl {
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(void *This, REFIID riid, void **ppvObject);
    ULONG (STDMETHODCALLTYPE *AddRef)(void *This);
    ULONG (STDMETHODCALLTYPE *Release)(void *This);
    void (STDMETHODCALLTYPE *GetFactory)(PDK_ID2D1Resource *This, PDK_ID2D1Factory **factory);
};

struct PDK_ID2D1RenderTargetVtbl {
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(void *This, REFIID riid, void **ppvObject);
    ULONG (STDMETHODCALLTYPE *AddRef)(void *This);
    ULONG (STDMETHODCALLTYPE *Release)(void *This);
    void (STDMETHODCALLTYPE *GetFactory)(PDK_ID2D1Resource *This, PDK_ID2D1Factory **factory);
    HRESULT (STDMETHODCALLTYPE *CreateBitmap)(PDK_ID2D1RenderTarget *This, D2D1_SIZE_U size, const void *srcData, UINT32 pitch, const D2D1_BITMAP_PROPERTIES *bitmapProperties, PDK_ID2D1Bitmap **bitmap);
    HRESULT (STDMETHODCALLTYPE *CreateBitmapFromWicBitmap)(PDK_ID2D1RenderTarget *This, void *wicBitmapSource, const D2D1_BITMAP_PROPERTIES *bitmapProperties, PDK_ID2D1Bitmap **bitmap);
    HRESULT (STDMETHODCALLTYPE *CreateSharedBitmap)(PDK_ID2D1RenderTarget *This, REFIID riid, void *data, const D2D1_BITMAP_PROPERTIES *bitmapProperties, PDK_ID2D1Bitmap **bitmap);
    HRESULT (STDMETHODCALLTYPE *CreateBitmapBrush)(PDK_ID2D1RenderTarget *This, PDK_ID2D1Bitmap *bitmap, const D2D1_BITMAP_BRUSH_PROPERTIES *bitmapBrushProperties, const D2D1_BRUSH_PROPERTIES *brushProperties, PDK_ID2D1BitmapBrush **bitmapBrush);
    HRESULT (STDMETHODCALLTYPE *CreateSolidColorBrush)(PDK_ID2D1RenderTarget *This, const D2D1_COLOR_F *color, const D2D1_BRUSH_PROPERTIES *brushProperties, PDK_ID2D1SolidColorBrush **solidColorBrush);
    HRESULT (STDMETHODCALLTYPE *CreateGradientStopCollection)(PDK_ID2D1RenderTarget *This, const D2D1_GRADIENT_STOP *gradientStops, UINT gradientStopsCount, D2D1_GAMMA colorInterpolationGamma, D2D1_EXTEND_MODE extendMode, PDK_ID2D1GradientStopCollection **gradientStopCollection);
    HRESULT (STDMETHODCALLTYPE *CreateLinearGradientBrush)(PDK_ID2D1RenderTarget *This, const D2D1_LINEAR_GRADIENT_BRUSH_PROPERTIES *linearGradientBrushProperties, const D2D1_BRUSH_PROPERTIES *brushProperties, PDK_ID2D1GradientStopCollection *gradientStopCollection, PDK_ID2D1LinearGradientBrush **linearGradientBrush);
    HRESULT (STDMETHODCALLTYPE *CreateRadialGradientBrush)(PDK_ID2D1RenderTarget *This, const D2D1_RADIAL_GRADIENT_BRUSH_PROPERTIES *radialGradientBrushProperties, const D2D1_BRUSH_PROPERTIES *brushProperties, PDK_ID2D1GradientStopCollection *gradientStopCollection, PDK_ID2D1RadialGradientBrush **radialGradientBrush);
    HRESULT (STDMETHODCALLTYPE *CreateCompatibleRenderTarget)(PDK_ID2D1RenderTarget *This, const D2D1_SIZE_F *desiredSize, const D2D1_SIZE_U *desiredPixelSize, const D2D1_PIXEL_FORMAT *desiredFormat, D2D1_COMPATIBLE_RENDER_TARGET_OPTIONS options, void **bitmapRenderTarget);
    HRESULT (STDMETHODCALLTYPE *CreateLayer)(PDK_ID2D1RenderTarget *This, const D2D1_SIZE_F *size, void **layer);
    HRESULT (STDMETHODCALLTYPE *CreateMesh)(PDK_ID2D1RenderTarget *This, void **mesh);
    void (STDMETHODCALLTYPE *DrawLine)(PDK_ID2D1RenderTarget *This, D2D1_POINT_2F point0, D2D1_POINT_2F point1, PDK_ID2D1Brush *brush, FLOAT strokeWidth, PDK_ID2D1StrokeStyle *strokeStyle);
    void (STDMETHODCALLTYPE *DrawRectangle)(PDK_ID2D1RenderTarget *This, const D2D1_RECT_F *rect, PDK_ID2D1Brush *brush, FLOAT strokeWidth, PDK_ID2D1StrokeStyle *strokeStyle);
    void (STDMETHODCALLTYPE *FillRectangle)(PDK_ID2D1RenderTarget *This, const D2D1_RECT_F *rect, PDK_ID2D1Brush *brush);
    void (STDMETHODCALLTYPE *DrawRoundedRectangle)(PDK_ID2D1RenderTarget *This, const D2D1_ROUNDED_RECT *roundedRect, PDK_ID2D1Brush *brush, FLOAT strokeWidth, PDK_ID2D1StrokeStyle *strokeStyle);
    void (STDMETHODCALLTYPE *FillRoundedRectangle)(PDK_ID2D1RenderTarget *This, const D2D1_ROUNDED_RECT *roundedRect, PDK_ID2D1Brush *brush);
    void (STDMETHODCALLTYPE *DrawEllipse)(PDK_ID2D1RenderTarget *This, const D2D1_ELLIPSE *ellipse, PDK_ID2D1Brush *brush, FLOAT strokeWidth, PDK_ID2D1StrokeStyle *strokeStyle);
    void (STDMETHODCALLTYPE *FillEllipse)(PDK_ID2D1RenderTarget *This, const D2D1_ELLIPSE *ellipse, PDK_ID2D1Brush *brush);
    void (STDMETHODCALLTYPE *DrawGeometry)(PDK_ID2D1RenderTarget *This, PDK_ID2D1Geometry *geometry, PDK_ID2D1Brush *brush, FLOAT strokeWidth, PDK_ID2D1StrokeStyle *strokeStyle);
    void (STDMETHODCALLTYPE *FillGeometry)(PDK_ID2D1RenderTarget *This, PDK_ID2D1Geometry *geometry, PDK_ID2D1Brush *brush, PDK_ID2D1Brush *opacityBrush);
    void (STDMETHODCALLTYPE *FillMesh)(PDK_ID2D1RenderTarget *This, void *mesh, PDK_ID2D1Brush *brush);
    void (STDMETHODCALLTYPE *FillOpacityMask)(PDK_ID2D1RenderTarget *This, PDK_ID2D1Bitmap *opacityMask, PDK_ID2D1Brush *brush, D2D1_OPACITY_MASK_CONTENT content, const D2D1_RECT_F *destinationRectangle, const D2D1_RECT_F *sourceRectangle);
    void (STDMETHODCALLTYPE *DrawBitmap)(PDK_ID2D1RenderTarget *This, PDK_ID2D1Bitmap *bitmap, const D2D1_RECT_F *destinationRectangle, FLOAT opacity, D2D1_BITMAP_INTERPOLATION_MODE interpolationMode, const D2D1_RECT_F *sourceRectangle);
    void (STDMETHODCALLTYPE *DrawText)(PDK_ID2D1RenderTarget *This, const WCHAR *string, UINT stringLength, PDK_IDWriteTextFormat *textFormat, const D2D1_RECT_F *layoutRect, PDK_ID2D1Brush *defaultForegroundBrush, D2D1_DRAW_TEXT_OPTIONS options, DWRITE_MEASURING_MODE measuringMode);
    void (STDMETHODCALLTYPE *DrawTextLayout)(PDK_ID2D1RenderTarget *This, D2D1_POINT_2F origin, PDK_IDWriteTextLayout *textLayout, PDK_ID2D1Brush *defaultForegroundBrush, D2D1_DRAW_TEXT_OPTIONS options);
    void (STDMETHODCALLTYPE *DrawGlyphRun)(PDK_ID2D1RenderTarget *This, D2D1_POINT_2F baselineOrigin, const DWRITE_GLYPH_RUN *glyphRun, PDK_ID2D1Brush *foregroundBrush, DWRITE_MEASURING_MODE measuringMode);
    void (STDMETHODCALLTYPE *SetTransform)(PDK_ID2D1RenderTarget *This, const D2D1_MATRIX_3X2_F *transform);
    void (STDMETHODCALLTYPE *GetTransform)(PDK_ID2D1RenderTarget *This, D2D1_MATRIX_3X2_F *transform);
    void (STDMETHODCALLTYPE *SetAntialiasMode)(PDK_ID2D1RenderTarget *This, D2D1_ANTIALIAS_MODE antialiasMode);
    D2D1_ANTIALIAS_MODE (STDMETHODCALLTYPE *GetAntialiasMode)(PDK_ID2D1RenderTarget *This);
    void (STDMETHODCALLTYPE *SetTextAntialiasMode)(PDK_ID2D1RenderTarget *This, D2D1_TEXT_ANTIALIAS_MODE textAntialiasMode);
    D2D1_TEXT_ANTIALIAS_MODE (STDMETHODCALLTYPE *GetTextAntialiasMode)(PDK_ID2D1RenderTarget *This);
    void (STDMETHODCALLTYPE *SetTextRenderingParams)(PDK_ID2D1RenderTarget *This, void *textRenderingParams);
    void (STDMETHODCALLTYPE *GetTextRenderingParams)(PDK_ID2D1RenderTarget *This, void **textRenderingParams);
    void (STDMETHODCALLTYPE *SetTags)(PDK_ID2D1RenderTarget *This, D2D1_TAG tag1, D2D1_TAG tag2);
    void (STDMETHODCALLTYPE *GetTags)(PDK_ID2D1RenderTarget *This, D2D1_TAG *tag1, D2D1_TAG *tag2);
    void (STDMETHODCALLTYPE *PushLayer)(PDK_ID2D1RenderTarget *This, const D2D1_LAYER_PARAMETERS *layerParameters, void *layer);
    void (STDMETHODCALLTYPE *PopLayer)(PDK_ID2D1RenderTarget *This);
    HRESULT (STDMETHODCALLTYPE *Flush)(PDK_ID2D1RenderTarget *This, D2D1_TAG *tag1, D2D1_TAG *tag2);
    void (STDMETHODCALLTYPE *SaveDrawingState)(PDK_ID2D1RenderTarget *This, void *drawingStateBlock);
    void (STDMETHODCALLTYPE *RestoreDrawingState)(PDK_ID2D1RenderTarget *This, void *drawingStateBlock);
    void (STDMETHODCALLTYPE *PushAxisAlignedClip)(PDK_ID2D1RenderTarget *This, const D2D1_RECT_F *clipRect, D2D1_ANTIALIAS_MODE antialiasMode);
    void (STDMETHODCALLTYPE *PopAxisAlignedClip)(PDK_ID2D1RenderTarget *This);
    void (STDMETHODCALLTYPE *Clear)(PDK_ID2D1RenderTarget *This, const D2D1_COLOR_F *clearColor);
    void (STDMETHODCALLTYPE *BeginDraw)(PDK_ID2D1RenderTarget *This);
    HRESULT (STDMETHODCALLTYPE *EndDraw)(PDK_ID2D1RenderTarget *This, D2D1_TAG *tag1, D2D1_TAG *tag2);
    D2D1_PIXEL_FORMAT (STDMETHODCALLTYPE *GetPixelFormat)(PDK_ID2D1RenderTarget *This);
    void (STDMETHODCALLTYPE *SetDpi)(PDK_ID2D1RenderTarget *This, FLOAT dpiX, FLOAT dpiY);
    void (STDMETHODCALLTYPE *GetDpi)(PDK_ID2D1RenderTarget *This, FLOAT *dpiX, FLOAT *dpiY);
    D2D1_SIZE_F (STDMETHODCALLTYPE *GetSize)(PDK_ID2D1RenderTarget *This);
    D2D1_SIZE_U (STDMETHODCALLTYPE *GetPixelSize)(PDK_ID2D1RenderTarget *This);
    UINT32 (STDMETHODCALLTYPE *GetMaximumBitmapSize)(PDK_ID2D1RenderTarget *This);
    BOOL (STDMETHODCALLTYPE *IsSupported)(PDK_ID2D1RenderTarget *This, const D2D1_RENDER_TARGET_PROPERTIES *renderTargetProperties);
};

struct PDK_ID2D1HwndRenderTargetVtbl {
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(void *This, REFIID riid, void **ppvObject);
    ULONG (STDMETHODCALLTYPE *AddRef)(void *This);
    ULONG (STDMETHODCALLTYPE *Release)(void *This);
    void (STDMETHODCALLTYPE *GetFactory)(PDK_ID2D1Resource *This, PDK_ID2D1Factory **factory);
    HRESULT (STDMETHODCALLTYPE *CreateBitmap)(PDK_ID2D1RenderTarget *This, D2D1_SIZE_U size, const void *srcData, UINT32 pitch, const D2D1_BITMAP_PROPERTIES *bitmapProperties, PDK_ID2D1Bitmap **bitmap);
    HRESULT (STDMETHODCALLTYPE *CreateBitmapFromWicBitmap)(PDK_ID2D1RenderTarget *This, void *wicBitmapSource, const D2D1_BITMAP_PROPERTIES *bitmapProperties, PDK_ID2D1Bitmap **bitmap);
    HRESULT (STDMETHODCALLTYPE *CreateSharedBitmap)(PDK_ID2D1RenderTarget *This, REFIID riid, void *data, const D2D1_BITMAP_PROPERTIES *bitmapProperties, PDK_ID2D1Bitmap **bitmap);
    HRESULT (STDMETHODCALLTYPE *CreateBitmapBrush)(PDK_ID2D1RenderTarget *This, PDK_ID2D1Bitmap *bitmap, const D2D1_BITMAP_BRUSH_PROPERTIES *bitmapBrushProperties, const D2D1_BRUSH_PROPERTIES *brushProperties, PDK_ID2D1BitmapBrush **bitmapBrush);
    HRESULT (STDMETHODCALLTYPE *CreateSolidColorBrush)(PDK_ID2D1RenderTarget *This, const D2D1_COLOR_F *color, const D2D1_BRUSH_PROPERTIES *brushProperties, PDK_ID2D1SolidColorBrush **solidColorBrush);
    HRESULT (STDMETHODCALLTYPE *CreateGradientStopCollection)(PDK_ID2D1RenderTarget *This, const D2D1_GRADIENT_STOP *gradientStops, UINT gradientStopsCount, D2D1_GAMMA colorInterpolationGamma, D2D1_EXTEND_MODE extendMode, PDK_ID2D1GradientStopCollection **gradientStopCollection);
    HRESULT (STDMETHODCALLTYPE *CreateLinearGradientBrush)(PDK_ID2D1RenderTarget *This, const D2D1_LINEAR_GRADIENT_BRUSH_PROPERTIES *linearGradientBrushProperties, const D2D1_BRUSH_PROPERTIES *brushProperties, PDK_ID2D1GradientStopCollection *gradientStopCollection, PDK_ID2D1LinearGradientBrush **linearGradientBrush);
    HRESULT (STDMETHODCALLTYPE *CreateRadialGradientBrush)(PDK_ID2D1RenderTarget *This, const D2D1_RADIAL_GRADIENT_BRUSH_PROPERTIES *radialGradientBrushProperties, const D2D1_BRUSH_PROPERTIES *brushProperties, PDK_ID2D1GradientStopCollection *gradientStopCollection, PDK_ID2D1RadialGradientBrush **radialGradientBrush);
    HRESULT (STDMETHODCALLTYPE *CreateCompatibleRenderTarget)(PDK_ID2D1RenderTarget *This, const D2D1_SIZE_F *desiredSize, const D2D1_SIZE_U *desiredPixelSize, const D2D1_PIXEL_FORMAT *desiredFormat, D2D1_COMPATIBLE_RENDER_TARGET_OPTIONS options, void **bitmapRenderTarget);
    HRESULT (STDMETHODCALLTYPE *CreateLayer)(PDK_ID2D1RenderTarget *This, const D2D1_SIZE_F *size, void **layer);
    HRESULT (STDMETHODCALLTYPE *CreateMesh)(PDK_ID2D1RenderTarget *This, void **mesh);
    void (STDMETHODCALLTYPE *DrawLine)(PDK_ID2D1RenderTarget *This, D2D1_POINT_2F point0, D2D1_POINT_2F point1, PDK_ID2D1Brush *brush, FLOAT strokeWidth, PDK_ID2D1StrokeStyle *strokeStyle);
    void (STDMETHODCALLTYPE *DrawRectangle)(PDK_ID2D1RenderTarget *This, const D2D1_RECT_F *rect, PDK_ID2D1Brush *brush, FLOAT strokeWidth, PDK_ID2D1StrokeStyle *strokeStyle);
    void (STDMETHODCALLTYPE *FillRectangle)(PDK_ID2D1RenderTarget *This, const D2D1_RECT_F *rect, PDK_ID2D1Brush *brush);
    void (STDMETHODCALLTYPE *DrawRoundedRectangle)(PDK_ID2D1RenderTarget *This, const D2D1_ROUNDED_RECT *roundedRect, PDK_ID2D1Brush *brush, FLOAT strokeWidth, PDK_ID2D1StrokeStyle *strokeStyle);
    void (STDMETHODCALLTYPE *FillRoundedRectangle)(PDK_ID2D1RenderTarget *This, const D2D1_ROUNDED_RECT *roundedRect, PDK_ID2D1Brush *brush);
    void (STDMETHODCALLTYPE *DrawEllipse)(PDK_ID2D1RenderTarget *This, const D2D1_ELLIPSE *ellipse, PDK_ID2D1Brush *brush, FLOAT strokeWidth, PDK_ID2D1StrokeStyle *strokeStyle);
    void (STDMETHODCALLTYPE *FillEllipse)(PDK_ID2D1RenderTarget *This, const D2D1_ELLIPSE *ellipse, PDK_ID2D1Brush *brush);
    void (STDMETHODCALLTYPE *DrawGeometry)(PDK_ID2D1RenderTarget *This, PDK_ID2D1Geometry *geometry, PDK_ID2D1Brush *brush, FLOAT strokeWidth, PDK_ID2D1StrokeStyle *strokeStyle);
    void (STDMETHODCALLTYPE *FillGeometry)(PDK_ID2D1RenderTarget *This, PDK_ID2D1Geometry *geometry, PDK_ID2D1Brush *brush, PDK_ID2D1Brush *opacityBrush);
    void (STDMETHODCALLTYPE *FillMesh)(PDK_ID2D1RenderTarget *This, void *mesh, PDK_ID2D1Brush *brush);
    void (STDMETHODCALLTYPE *FillOpacityMask)(PDK_ID2D1RenderTarget *This, PDK_ID2D1Bitmap *opacityMask, PDK_ID2D1Brush *brush, D2D1_OPACITY_MASK_CONTENT content, const D2D1_RECT_F *destinationRectangle, const D2D1_RECT_F *sourceRectangle);
    void (STDMETHODCALLTYPE *DrawBitmap)(PDK_ID2D1RenderTarget *This, PDK_ID2D1Bitmap *bitmap, const D2D1_RECT_F *destinationRectangle, FLOAT opacity, D2D1_BITMAP_INTERPOLATION_MODE interpolationMode, const D2D1_RECT_F *sourceRectangle);
    void (STDMETHODCALLTYPE *DrawText)(PDK_ID2D1RenderTarget *This, const WCHAR *string, UINT stringLength, PDK_IDWriteTextFormat *textFormat, const D2D1_RECT_F *layoutRect, PDK_ID2D1Brush *defaultForegroundBrush, D2D1_DRAW_TEXT_OPTIONS options, DWRITE_MEASURING_MODE measuringMode);
    void (STDMETHODCALLTYPE *DrawTextLayout)(PDK_ID2D1RenderTarget *This, D2D1_POINT_2F origin, PDK_IDWriteTextLayout *textLayout, PDK_ID2D1Brush *defaultForegroundBrush, D2D1_DRAW_TEXT_OPTIONS options);
    void (STDMETHODCALLTYPE *DrawGlyphRun)(PDK_ID2D1RenderTarget *This, D2D1_POINT_2F baselineOrigin, const DWRITE_GLYPH_RUN *glyphRun, PDK_ID2D1Brush *foregroundBrush, DWRITE_MEASURING_MODE measuringMode);
    void (STDMETHODCALLTYPE *SetTransform)(PDK_ID2D1RenderTarget *This, const D2D1_MATRIX_3X2_F *transform);
    void (STDMETHODCALLTYPE *GetTransform)(PDK_ID2D1RenderTarget *This, D2D1_MATRIX_3X2_F *transform);
    void (STDMETHODCALLTYPE *SetAntialiasMode)(PDK_ID2D1RenderTarget *This, D2D1_ANTIALIAS_MODE antialiasMode);
    D2D1_ANTIALIAS_MODE (STDMETHODCALLTYPE *GetAntialiasMode)(PDK_ID2D1RenderTarget *This);
    void (STDMETHODCALLTYPE *SetTextAntialiasMode)(PDK_ID2D1RenderTarget *This, D2D1_TEXT_ANTIALIAS_MODE textAntialiasMode);
    D2D1_TEXT_ANTIALIAS_MODE (STDMETHODCALLTYPE *GetTextAntialiasMode)(PDK_ID2D1RenderTarget *This);
    void (STDMETHODCALLTYPE *SetTextRenderingParams)(PDK_ID2D1RenderTarget *This, void *textRenderingParams);
    void (STDMETHODCALLTYPE *GetTextRenderingParams)(PDK_ID2D1RenderTarget *This, void **textRenderingParams);
    void (STDMETHODCALLTYPE *SetTags)(PDK_ID2D1RenderTarget *This, D2D1_TAG tag1, D2D1_TAG tag2);
    void (STDMETHODCALLTYPE *GetTags)(PDK_ID2D1RenderTarget *This, D2D1_TAG *tag1, D2D1_TAG *tag2);
    void (STDMETHODCALLTYPE *PushLayer)(PDK_ID2D1RenderTarget *This, const D2D1_LAYER_PARAMETERS *layerParameters, void *layer);
    void (STDMETHODCALLTYPE *PopLayer)(PDK_ID2D1RenderTarget *This);
    HRESULT (STDMETHODCALLTYPE *Flush)(PDK_ID2D1RenderTarget *This, D2D1_TAG *tag1, D2D1_TAG *tag2);
    void (STDMETHODCALLTYPE *SaveDrawingState)(PDK_ID2D1RenderTarget *This, void *drawingStateBlock);
    void (STDMETHODCALLTYPE *RestoreDrawingState)(PDK_ID2D1RenderTarget *This, void *drawingStateBlock);
    void (STDMETHODCALLTYPE *PushAxisAlignedClip)(PDK_ID2D1RenderTarget *This, const D2D1_RECT_F *clipRect, D2D1_ANTIALIAS_MODE antialiasMode);
    void (STDMETHODCALLTYPE *PopAxisAlignedClip)(PDK_ID2D1RenderTarget *This);
    void (STDMETHODCALLTYPE *Clear)(PDK_ID2D1RenderTarget *This, const D2D1_COLOR_F *clearColor);
    void (STDMETHODCALLTYPE *BeginDraw)(PDK_ID2D1RenderTarget *This);
    HRESULT (STDMETHODCALLTYPE *EndDraw)(PDK_ID2D1RenderTarget *This, D2D1_TAG *tag1, D2D1_TAG *tag2);
    D2D1_PIXEL_FORMAT (STDMETHODCALLTYPE *GetPixelFormat)(PDK_ID2D1RenderTarget *This);
    void (STDMETHODCALLTYPE *SetDpi)(PDK_ID2D1RenderTarget *This, FLOAT dpiX, FLOAT dpiY);
    void (STDMETHODCALLTYPE *GetDpi)(PDK_ID2D1RenderTarget *This, FLOAT *dpiX, FLOAT *dpiY);
    D2D1_SIZE_F (STDMETHODCALLTYPE *GetSize)(PDK_ID2D1RenderTarget *This);
    D2D1_SIZE_U (STDMETHODCALLTYPE *GetPixelSize)(PDK_ID2D1RenderTarget *This);
    UINT32 (STDMETHODCALLTYPE *GetMaximumBitmapSize)(PDK_ID2D1RenderTarget *This);
    BOOL (STDMETHODCALLTYPE *IsSupported)(PDK_ID2D1RenderTarget *This, const D2D1_RENDER_TARGET_PROPERTIES *renderTargetProperties);
    D2D1_WINDOW_STATE (STDMETHODCALLTYPE *CheckWindowState)(PDK_ID2D1HwndRenderTarget *This);
    HRESULT (STDMETHODCALLTYPE *Resize)(PDK_ID2D1HwndRenderTarget *This, const D2D1_SIZE_U *pixelSize);
    HWND (STDMETHODCALLTYPE *GetHwnd)(PDK_ID2D1HwndRenderTarget *This);
};

struct PDK_ID2D1BrushVtbl {
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(void *This, REFIID riid, void **ppvObject);
    ULONG (STDMETHODCALLTYPE *AddRef)(void *This);
    ULONG (STDMETHODCALLTYPE *Release)(void *This);
    void (STDMETHODCALLTYPE *GetFactory)(PDK_ID2D1Resource *This, PDK_ID2D1Factory **factory);
    void (STDMETHODCALLTYPE *SetOpacity)(PDK_ID2D1Brush *This, FLOAT opacity);
    void (STDMETHODCALLTYPE *SetTransform)(PDK_ID2D1Brush *This, const D2D1_MATRIX_3X2_F *transform);
    FLOAT (STDMETHODCALLTYPE *GetOpacity)(PDK_ID2D1Brush *This);
    void (STDMETHODCALLTYPE *GetTransform)(PDK_ID2D1Brush *This, D2D1_MATRIX_3X2_F *transform);
};

struct PDK_ID2D1SolidColorBrushVtbl {
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(void *This, REFIID riid, void **ppvObject);
    ULONG (STDMETHODCALLTYPE *AddRef)(void *This);
    ULONG (STDMETHODCALLTYPE *Release)(void *This);
    void (STDMETHODCALLTYPE *GetFactory)(PDK_ID2D1Resource *This, PDK_ID2D1Factory **factory);
    void (STDMETHODCALLTYPE *SetOpacity)(PDK_ID2D1Brush *This, FLOAT opacity);
    void (STDMETHODCALLTYPE *SetTransform)(PDK_ID2D1Brush *This, const D2D1_MATRIX_3X2_F *transform);
    FLOAT (STDMETHODCALLTYPE *GetOpacity)(PDK_ID2D1Brush *This);
    void (STDMETHODCALLTYPE *GetTransform)(PDK_ID2D1Brush *This, D2D1_MATRIX_3X2_F *transform);
    void (STDMETHODCALLTYPE *SetColor)(PDK_ID2D1SolidColorBrush *This, const D2D1_COLOR_F *color);
    D2D1_COLOR_F (STDMETHODCALLTYPE *GetColor)(PDK_ID2D1SolidColorBrush *This);
};

struct PDK_ID2D1LinearGradientBrushVtbl {
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(void *This, REFIID riid, void **ppvObject);
    ULONG (STDMETHODCALLTYPE *AddRef)(void *This);
    ULONG (STDMETHODCALLTYPE *Release)(void *This);
    void (STDMETHODCALLTYPE *GetFactory)(PDK_ID2D1Resource *This, PDK_ID2D1Factory **factory);
    void (STDMETHODCALLTYPE *SetOpacity)(PDK_ID2D1Brush *This, FLOAT opacity);
    void (STDMETHODCALLTYPE *SetTransform)(PDK_ID2D1Brush *This, const D2D1_MATRIX_3X2_F *transform);
    FLOAT (STDMETHODCALLTYPE *GetOpacity)(PDK_ID2D1Brush *This);
    void (STDMETHODCALLTYPE *GetTransform)(PDK_ID2D1Brush *This, D2D1_MATRIX_3X2_F *transform);
    void (STDMETHODCALLTYPE *SetStartPoint)(PDK_ID2D1LinearGradientBrush *This, D2D1_POINT_2F startPoint);
    void (STDMETHODCALLTYPE *SetEndPoint)(PDK_ID2D1LinearGradientBrush *This, D2D1_POINT_2F endPoint);
    D2D1_POINT_2F (STDMETHODCALLTYPE *GetStartPoint)(PDK_ID2D1LinearGradientBrush *This);
    D2D1_POINT_2F (STDMETHODCALLTYPE *GetEndPoint)(PDK_ID2D1LinearGradientBrush *This);
    void (STDMETHODCALLTYPE *GetGradientStopCollection)(PDK_ID2D1LinearGradientBrush *This, PDK_ID2D1GradientStopCollection **gradientStopCollection);
};

struct PDK_ID2D1RadialGradientBrushVtbl {
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(void *This, REFIID riid, void **ppvObject);
    ULONG (STDMETHODCALLTYPE *AddRef)(void *This);
    ULONG (STDMETHODCALLTYPE *Release)(void *This);
    void (STDMETHODCALLTYPE *GetFactory)(PDK_ID2D1Resource *This, PDK_ID2D1Factory **factory);
    void (STDMETHODCALLTYPE *SetOpacity)(PDK_ID2D1Brush *This, FLOAT opacity);
    void (STDMETHODCALLTYPE *SetTransform)(PDK_ID2D1Brush *This, const D2D1_MATRIX_3X2_F *transform);
    FLOAT (STDMETHODCALLTYPE *GetOpacity)(PDK_ID2D1Brush *This);
    void (STDMETHODCALLTYPE *GetTransform)(PDK_ID2D1Brush *This, D2D1_MATRIX_3X2_F *transform);
    void (STDMETHODCALLTYPE *SetCenter)(PDK_ID2D1RadialGradientBrush *This, D2D1_POINT_2F center);
    void (STDMETHODCALLTYPE *SetGradientOriginOffset)(PDK_ID2D1RadialGradientBrush *This, D2D1_POINT_2F gradientOriginOffset);
    void (STDMETHODCALLTYPE *SetRadiusX)(PDK_ID2D1RadialGradientBrush *This, FLOAT radiusX);
    void (STDMETHODCALLTYPE *SetRadiusY)(PDK_ID2D1RadialGradientBrush *This, FLOAT radiusY);
    D2D1_POINT_2F (STDMETHODCALLTYPE *GetCenter)(PDK_ID2D1RadialGradientBrush *This);
    D2D1_POINT_2F (STDMETHODCALLTYPE *GetGradientOriginOffset)(PDK_ID2D1RadialGradientBrush *This);
    FLOAT (STDMETHODCALLTYPE *GetRadiusX)(PDK_ID2D1RadialGradientBrush *This);
    FLOAT (STDMETHODCALLTYPE *GetRadiusY)(PDK_ID2D1RadialGradientBrush *This);
    void (STDMETHODCALLTYPE *GetGradientStopCollection)(PDK_ID2D1RadialGradientBrush *This, PDK_ID2D1GradientStopCollection **gradientStopCollection);
};

struct PDK_ID2D1BitmapBrushVtbl {
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(void *This, REFIID riid, void **ppvObject);
    ULONG (STDMETHODCALLTYPE *AddRef)(void *This);
    ULONG (STDMETHODCALLTYPE *Release)(void *This);
    void (STDMETHODCALLTYPE *GetFactory)(PDK_ID2D1Resource *This, PDK_ID2D1Factory **factory);
    void (STDMETHODCALLTYPE *SetOpacity)(PDK_ID2D1Brush *This, FLOAT opacity);
    void (STDMETHODCALLTYPE *SetTransform)(PDK_ID2D1Brush *This, const D2D1_MATRIX_3X2_F *transform);
    FLOAT (STDMETHODCALLTYPE *GetOpacity)(PDK_ID2D1Brush *This);
    void (STDMETHODCALLTYPE *GetTransform)(PDK_ID2D1Brush *This, D2D1_MATRIX_3X2_F *transform);
    void (STDMETHODCALLTYPE *SetExtendModeX)(PDK_ID2D1BitmapBrush *This, D2D1_EXTEND_MODE extendModeX);
    void (STDMETHODCALLTYPE *SetExtendModeY)(PDK_ID2D1BitmapBrush *This, D2D1_EXTEND_MODE extendModeY);
    void (STDMETHODCALLTYPE *SetInterpolationMode)(PDK_ID2D1BitmapBrush *This, D2D1_BITMAP_INTERPOLATION_MODE interpolationMode);
    void (STDMETHODCALLTYPE *SetBitmap)(PDK_ID2D1BitmapBrush *This, PDK_ID2D1Bitmap *bitmap);
    D2D1_EXTEND_MODE (STDMETHODCALLTYPE *GetExtendModeX)(PDK_ID2D1BitmapBrush *This);
    D2D1_EXTEND_MODE (STDMETHODCALLTYPE *GetExtendModeY)(PDK_ID2D1BitmapBrush *This);
    D2D1_BITMAP_INTERPOLATION_MODE (STDMETHODCALLTYPE *GetInterpolationMode)(PDK_ID2D1BitmapBrush *This);
    void (STDMETHODCALLTYPE *GetBitmap)(PDK_ID2D1BitmapBrush *This, PDK_ID2D1Bitmap **bitmap);
};

struct PDK_ID2D1ImageVtbl {
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(void *This, REFIID riid, void **ppvObject);
    ULONG (STDMETHODCALLTYPE *AddRef)(void *This);
    ULONG (STDMETHODCALLTYPE *Release)(void *This);
    void (STDMETHODCALLTYPE *GetFactory)(PDK_ID2D1Resource *This, PDK_ID2D1Factory **factory);
};

struct PDK_ID2D1BitmapVtbl {
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(void *This, REFIID riid, void **ppvObject);
    ULONG (STDMETHODCALLTYPE *AddRef)(void *This);
    ULONG (STDMETHODCALLTYPE *Release)(void *This);
    void (STDMETHODCALLTYPE *GetFactory)(PDK_ID2D1Resource *This, PDK_ID2D1Factory **factory);
    D2D1_SIZE_F (STDMETHODCALLTYPE *GetSize)(PDK_ID2D1Bitmap *This);
    D2D1_SIZE_U (STDMETHODCALLTYPE *GetPixelSize)(PDK_ID2D1Bitmap *This);
    D2D1_PIXEL_FORMAT (STDMETHODCALLTYPE *GetPixelFormat)(PDK_ID2D1Bitmap *This);
    void (STDMETHODCALLTYPE *GetDpi)(PDK_ID2D1Bitmap *This, FLOAT *dpiX, FLOAT *dpiY);
    HRESULT (STDMETHODCALLTYPE *CopyFromBitmap)(PDK_ID2D1Bitmap *This, const D2D1_POINT_2U *destPoint, PDK_ID2D1Bitmap *bitmap, const D2D1_RECT_U *srcRect);
    HRESULT (STDMETHODCALLTYPE *CopyFromRenderTarget)(PDK_ID2D1Bitmap *This, const D2D1_POINT_2U *destPoint, PDK_ID2D1RenderTarget *renderTarget, const D2D1_RECT_U *srcRect);
    HRESULT (STDMETHODCALLTYPE *CopyFromMemory)(PDK_ID2D1Bitmap *This, const D2D1_RECT_U *dstRect, const void *srcData, UINT32 pitch);
};

struct PDK_ID2D1GradientStopCollectionVtbl {
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(void *This, REFIID riid, void **ppvObject);
    ULONG (STDMETHODCALLTYPE *AddRef)(void *This);
    ULONG (STDMETHODCALLTYPE *Release)(void *This);
    void (STDMETHODCALLTYPE *GetFactory)(PDK_ID2D1Resource *This, PDK_ID2D1Factory **factory);
    UINT32 (STDMETHODCALLTYPE *GetGradientStopCount)(PDK_ID2D1GradientStopCollection *This);
    void (STDMETHODCALLTYPE *GetGradientStops)(PDK_ID2D1GradientStopCollection *This, D2D1_GRADIENT_STOP *gradientStops, UINT gradientStopsCount);
    D2D1_GAMMA (STDMETHODCALLTYPE *GetColorInterpolationGamma)(PDK_ID2D1GradientStopCollection *This);
    D2D1_EXTEND_MODE (STDMETHODCALLTYPE *GetExtendMode)(PDK_ID2D1GradientStopCollection *This);
};

struct PDK_ID2D1StrokeStyleVtbl {
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(void *This, REFIID riid, void **ppvObject);
    ULONG (STDMETHODCALLTYPE *AddRef)(void *This);
    ULONG (STDMETHODCALLTYPE *Release)(void *This);
    void (STDMETHODCALLTYPE *GetFactory)(PDK_ID2D1Resource *This, PDK_ID2D1Factory **factory);
    D2D1_CAP_STYLE (STDMETHODCALLTYPE *GetStartCap)(PDK_ID2D1StrokeStyle *This);
    D2D1_CAP_STYLE (STDMETHODCALLTYPE *GetEndCap)(PDK_ID2D1StrokeStyle *This);
    D2D1_CAP_STYLE (STDMETHODCALLTYPE *GetDashCap)(PDK_ID2D1StrokeStyle *This);
    FLOAT (STDMETHODCALLTYPE *GetMiterLimit)(PDK_ID2D1StrokeStyle *This);
    D2D1_LINE_JOIN (STDMETHODCALLTYPE *GetLineJoin)(PDK_ID2D1StrokeStyle *This);
    FLOAT (STDMETHODCALLTYPE *GetDashOffset)(PDK_ID2D1StrokeStyle *This);
    D2D1_DASH_STYLE (STDMETHODCALLTYPE *GetDashStyle)(PDK_ID2D1StrokeStyle *This);
    UINT32 (STDMETHODCALLTYPE *GetDashesCount)(PDK_ID2D1StrokeStyle *This);
    void (STDMETHODCALLTYPE *GetDashes)(PDK_ID2D1StrokeStyle *This, FLOAT *dashes, UINT dashesCount);
};

struct PDK_ID2D1GeometryVtbl {
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(void *This, REFIID riid, void **ppvObject);
    ULONG (STDMETHODCALLTYPE *AddRef)(void *This);
    ULONG (STDMETHODCALLTYPE *Release)(void *This);
    void (STDMETHODCALLTYPE *GetFactory)(PDK_ID2D1Resource *This, PDK_ID2D1Factory **factory);
    HRESULT (STDMETHODCALLTYPE *GetBounds)(PDK_ID2D1Geometry *This, const D2D1_MATRIX_3X2_F *worldTransform, D2D1_RECT_F *bounds);
    HRESULT (STDMETHODCALLTYPE *GetWidenedBounds)(PDK_ID2D1Geometry *This, FLOAT strokeWidth, PDK_ID2D1StrokeStyle *strokeStyle, const D2D1_MATRIX_3X2_F *worldTransform, FLOAT flatteningTolerance, D2D1_RECT_F *bounds);
    HRESULT (STDMETHODCALLTYPE *StrokeContainsPoint)(PDK_ID2D1Geometry *This, D2D1_POINT_2F point, FLOAT strokeWidth, PDK_ID2D1StrokeStyle *strokeStyle, const D2D1_MATRIX_3X2_F *worldTransform, FLOAT flatteningTolerance, BOOL *contains);
    HRESULT (STDMETHODCALLTYPE *FillContainsPoint)(PDK_ID2D1Geometry *This, D2D1_POINT_2F point, const D2D1_MATRIX_3X2_F *worldTransform, FLOAT flatteningTolerance, BOOL *contains);
    HRESULT (STDMETHODCALLTYPE *CompareWithGeometry)(PDK_ID2D1Geometry *This, PDK_ID2D1Geometry *inputGeometry, const D2D1_MATRIX_3X2_F *inputGeometryTransform, FLOAT flatteningTolerance, D2D1_GEOMETRY_RELATION *relation);
    HRESULT (STDMETHODCALLTYPE *Simplify)(PDK_ID2D1Geometry *This, D2D1_GEOMETRY_SIMPLIFICATION_OPTION simplificationOption, const D2D1_MATRIX_3X2_F *worldTransform, FLOAT flatteningTolerance, void *geometrySink);
    HRESULT (STDMETHODCALLTYPE *Tessellate)(PDK_ID2D1Geometry *This, const D2D1_MATRIX_3X2_F *worldTransform, FLOAT flatteningTolerance, void *tessellationSink);
    HRESULT (STDMETHODCALLTYPE *CombineWithGeometry)(PDK_ID2D1Geometry *This, PDK_ID2D1Geometry *inputGeometry, D2D1_COMBINE_MODE combineMode, const D2D1_MATRIX_3X2_F *inputGeometryTransform, FLOAT flatteningTolerance, void *geometrySink);
    HRESULT (STDMETHODCALLTYPE *Outline)(PDK_ID2D1Geometry *This, const D2D1_MATRIX_3X2_F *worldTransform, FLOAT flatteningTolerance, void *geometrySink);
    HRESULT (STDMETHODCALLTYPE *ComputeArea)(PDK_ID2D1Geometry *This, const D2D1_MATRIX_3X2_F *worldTransform, FLOAT flatteningTolerance, FLOAT *area);
    HRESULT (STDMETHODCALLTYPE *ComputeLength)(PDK_ID2D1Geometry *This, const D2D1_MATRIX_3X2_F *worldTransform, FLOAT flatteningTolerance, FLOAT *length);
    HRESULT (STDMETHODCALLTYPE *ComputePointAtLength)(PDK_ID2D1Geometry *This, FLOAT length, const D2D1_MATRIX_3X2_F *worldTransform, FLOAT flatteningTolerance, D2D1_POINT_2F *point, D2D1_POINT_2F *unitTangentVector);
    HRESULT (STDMETHODCALLTYPE *Widen)(PDK_ID2D1Geometry *This, FLOAT strokeWidth, PDK_ID2D1StrokeStyle *strokeStyle, const D2D1_MATRIX_3X2_F *worldTransform, FLOAT flatteningTolerance, void *geometrySink);
};

struct PDK_ID2D1PathGeometryVtbl {
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(void *This, REFIID riid, void **ppvObject);
    ULONG (STDMETHODCALLTYPE *AddRef)(void *This);
    ULONG (STDMETHODCALLTYPE *Release)(void *This);
    void (STDMETHODCALLTYPE *GetFactory)(PDK_ID2D1Resource *This, PDK_ID2D1Factory **factory);
    HRESULT (STDMETHODCALLTYPE *GetBounds)(PDK_ID2D1Geometry *This, const D2D1_MATRIX_3X2_F *worldTransform, D2D1_RECT_F *bounds);
    HRESULT (STDMETHODCALLTYPE *GetWidenedBounds)(PDK_ID2D1Geometry *This, FLOAT strokeWidth, PDK_ID2D1StrokeStyle *strokeStyle, const D2D1_MATRIX_3X2_F *worldTransform, FLOAT flatteningTolerance, D2D1_RECT_F *bounds);
    HRESULT (STDMETHODCALLTYPE *StrokeContainsPoint)(PDK_ID2D1Geometry *This, D2D1_POINT_2F point, FLOAT strokeWidth, PDK_ID2D1StrokeStyle *strokeStyle, const D2D1_MATRIX_3X2_F *worldTransform, FLOAT flatteningTolerance, BOOL *contains);
    HRESULT (STDMETHODCALLTYPE *FillContainsPoint)(PDK_ID2D1Geometry *This, D2D1_POINT_2F point, const D2D1_MATRIX_3X2_F *worldTransform, FLOAT flatteningTolerance, BOOL *contains);
    HRESULT (STDMETHODCALLTYPE *CompareWithGeometry)(PDK_ID2D1Geometry *This, PDK_ID2D1Geometry *inputGeometry, const D2D1_MATRIX_3X2_F *inputGeometryTransform, FLOAT flatteningTolerance, D2D1_GEOMETRY_RELATION *relation);
    HRESULT (STDMETHODCALLTYPE *Simplify)(PDK_ID2D1Geometry *This, D2D1_GEOMETRY_SIMPLIFICATION_OPTION simplificationOption, const D2D1_MATRIX_3X2_F *worldTransform, FLOAT flatteningTolerance, void *geometrySink);
    HRESULT (STDMETHODCALLTYPE *Tessellate)(PDK_ID2D1Geometry *This, const D2D1_MATRIX_3X2_F *worldTransform, FLOAT flatteningTolerance, void *tessellationSink);
    HRESULT (STDMETHODCALLTYPE *CombineWithGeometry)(PDK_ID2D1Geometry *This, PDK_ID2D1Geometry *inputGeometry, D2D1_COMBINE_MODE combineMode, const D2D1_MATRIX_3X2_F *inputGeometryTransform, FLOAT flatteningTolerance, void *geometrySink);
    HRESULT (STDMETHODCALLTYPE *Outline)(PDK_ID2D1Geometry *This, const D2D1_MATRIX_3X2_F *worldTransform, FLOAT flatteningTolerance, void *geometrySink);
    HRESULT (STDMETHODCALLTYPE *ComputeArea)(PDK_ID2D1Geometry *This, const D2D1_MATRIX_3X2_F *worldTransform, FLOAT flatteningTolerance, FLOAT *area);
    HRESULT (STDMETHODCALLTYPE *ComputeLength)(PDK_ID2D1Geometry *This, const D2D1_MATRIX_3X2_F *worldTransform, FLOAT flatteningTolerance, FLOAT *length);
    HRESULT (STDMETHODCALLTYPE *ComputePointAtLength)(PDK_ID2D1Geometry *This, FLOAT length, const D2D1_MATRIX_3X2_F *worldTransform, FLOAT flatteningTolerance, D2D1_POINT_2F *point, D2D1_POINT_2F *unitTangentVector);
    HRESULT (STDMETHODCALLTYPE *Widen)(PDK_ID2D1Geometry *This, FLOAT strokeWidth, PDK_ID2D1StrokeStyle *strokeStyle, const D2D1_MATRIX_3X2_F *worldTransform, FLOAT flatteningTolerance, void *geometrySink);
    HRESULT (STDMETHODCALLTYPE *Open)(PDK_ID2D1PathGeometry *This, PDK_ID2D1GeometrySink **geometrySink);
    HRESULT (STDMETHODCALLTYPE *Stream)(PDK_ID2D1PathGeometry *This, PDK_ID2D1GeometrySink *geometrySink);
    HRESULT (STDMETHODCALLTYPE *GetSegmentCount)(PDK_ID2D1PathGeometry *This, UINT32 *count);
    HRESULT (STDMETHODCALLTYPE *GetFigureCount)(PDK_ID2D1PathGeometry *This, UINT32 *count);
};

struct PDK_ID2D1GeometrySinkVtbl {
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(void *This, REFIID riid, void **ppvObject);
    ULONG (STDMETHODCALLTYPE *AddRef)(void *This);
    ULONG (STDMETHODCALLTYPE *Release)(void *This);
    void (STDMETHODCALLTYPE *SetFillMode)(void *This, D2D1_FILL_MODE fillMode);
    void (STDMETHODCALLTYPE *SetSegmentFlags)(void *This, D2D1_PATH_SEGMENT vertexFlags);
    void (STDMETHODCALLTYPE *BeginFigure)(void *This, D2D1_POINT_2F startPoint, D2D1_FIGURE_BEGIN figureBegin);
    void (STDMETHODCALLTYPE *AddLines)(void *This, const D2D1_POINT_2F *points, UINT pointsCount);
    void (STDMETHODCALLTYPE *AddBeziers)(void *This, const D2D1_BEZIER_SEGMENT *beziers, UINT beziersCount);
    void (STDMETHODCALLTYPE *EndFigure)(void *This, D2D1_FIGURE_END figureEnd);
    HRESULT (STDMETHODCALLTYPE *Close)(void *This);
    void (STDMETHODCALLTYPE *AddLine)(PDK_ID2D1GeometrySink *This, D2D1_POINT_2F point);
    void (STDMETHODCALLTYPE *AddBezier)(PDK_ID2D1GeometrySink *This, const D2D1_BEZIER_SEGMENT *bezier);
    void (STDMETHODCALLTYPE *AddQuadraticBezier)(PDK_ID2D1GeometrySink *This, const D2D1_QUADRATIC_BEZIER_SEGMENT *bezier);
    void (STDMETHODCALLTYPE *AddQuadraticBeziers)(PDK_ID2D1GeometrySink *This, const D2D1_QUADRATIC_BEZIER_SEGMENT *beziers, UINT beziersCount);
    void (STDMETHODCALLTYPE *AddArc)(PDK_ID2D1GeometrySink *This, const D2D1_ARC_SEGMENT *arc);
};

#endif /* PDK_SRC_GRAPHICS_D2D_C_H */
