/* AUTO-GENERATED by tools/gen_com_shim.py -- do not edit by hand.
 * Regenerate with: python tools/gen_com_shim.py
 * Source of truth: MinGW-w64 C-mode SDK headers; layout is verified at
 * compile time by tests/shim_layout (MinGW) -- see plan.md 3.3.
 */
#ifndef PDK_SRC_GRAPHICS_DWRITE_C_H
#define PDK_SRC_GRAPHICS_DWRITE_C_H
/* DirectWrite types and flat PDK vtables.
 * <dwrite.h> is deliberately NOT included: MSVC C mode cannot parse it
 * (dwrite.h:4704 uses C++ inheritance), so both toolchains consume these
 * definitions instead.  They are extracted verbatim from the MinGW-w64
 * header by tools/gen_com_shim.py and cross-checked against the real
 * <dwrite.h> by tests/shim_layout.
 *
 * Define PDK_SKIP_DWRITE_TYPES before including this header when the real
 * <dwrite.h> is already in scope (that is what tests/shim_layout does). */
#include "graphics/Com.h"
#include "graphics/iids_gen.h"

#ifndef PDK_SKIP_DWRITE_TYPES
/* ---- types (verbatim from MinGW-w64 <dwrite.h>) ---- */
/* supplied by <dcommon.h>: DWRITE_MEASURING_MODE */

typedef enum DWRITE_FACTORY_TYPE {
    DWRITE_FACTORY_TYPE_SHARED = 0,
    DWRITE_FACTORY_TYPE_ISOLATED = 1
} DWRITE_FACTORY_TYPE;

typedef enum DWRITE_FONT_WEIGHT {
    DWRITE_FONT_WEIGHT_THIN = 100,
    DWRITE_FONT_WEIGHT_EXTRA_LIGHT = 200,
    DWRITE_FONT_WEIGHT_ULTRA_LIGHT = 200,
    DWRITE_FONT_WEIGHT_LIGHT = 300,
    DWRITE_FONT_WEIGHT_SEMI_LIGHT = 350,
    DWRITE_FONT_WEIGHT_NORMAL = 400,
    DWRITE_FONT_WEIGHT_REGULAR = 400,
    DWRITE_FONT_WEIGHT_MEDIUM = 500,
    DWRITE_FONT_WEIGHT_DEMI_BOLD = 600,
    DWRITE_FONT_WEIGHT_SEMI_BOLD = 600,
    DWRITE_FONT_WEIGHT_BOLD = 700,
    DWRITE_FONT_WEIGHT_EXTRA_BOLD = 800,
    DWRITE_FONT_WEIGHT_ULTRA_BOLD = 800,
    DWRITE_FONT_WEIGHT_BLACK = 900,
    DWRITE_FONT_WEIGHT_HEAVY = 900,
    DWRITE_FONT_WEIGHT_EXTRA_BLACK = 950,
    DWRITE_FONT_WEIGHT_ULTRA_BLACK = 950
} DWRITE_FONT_WEIGHT;

typedef enum DWRITE_FONT_STRETCH {
    DWRITE_FONT_STRETCH_UNDEFINED = 0,
    DWRITE_FONT_STRETCH_ULTRA_CONDENSED = 1,
    DWRITE_FONT_STRETCH_EXTRA_CONDENSED = 2,
    DWRITE_FONT_STRETCH_CONDENSED = 3,
    DWRITE_FONT_STRETCH_SEMI_CONDENSED = 4,
    DWRITE_FONT_STRETCH_NORMAL = 5,
    DWRITE_FONT_STRETCH_MEDIUM = 5,
    DWRITE_FONT_STRETCH_SEMI_EXPANDED = 6,
    DWRITE_FONT_STRETCH_EXPANDED = 7,
    DWRITE_FONT_STRETCH_EXTRA_EXPANDED = 8,
    DWRITE_FONT_STRETCH_ULTRA_EXPANDED = 9
} DWRITE_FONT_STRETCH;

typedef enum DWRITE_FONT_STYLE {
    DWRITE_FONT_STYLE_NORMAL = 0,
    DWRITE_FONT_STYLE_OBLIQUE = 1,
    DWRITE_FONT_STYLE_ITALIC = 2
} DWRITE_FONT_STYLE;

typedef enum DWRITE_TEXT_ALIGNMENT {
    DWRITE_TEXT_ALIGNMENT_LEADING = 0,
    DWRITE_TEXT_ALIGNMENT_TRAILING = 1,
    DWRITE_TEXT_ALIGNMENT_CENTER = 2,
    DWRITE_TEXT_ALIGNMENT_JUSTIFIED = 3
} DWRITE_TEXT_ALIGNMENT;

typedef enum DWRITE_PARAGRAPH_ALIGNMENT {
    DWRITE_PARAGRAPH_ALIGNMENT_NEAR = 0,
    DWRITE_PARAGRAPH_ALIGNMENT_FAR = 1,
    DWRITE_PARAGRAPH_ALIGNMENT_CENTER = 2
} DWRITE_PARAGRAPH_ALIGNMENT;

typedef enum DWRITE_WORD_WRAPPING {
    DWRITE_WORD_WRAPPING_WRAP = 0,
    DWRITE_WORD_WRAPPING_NO_WRAP = 1,
    DWRITE_WORD_WRAPPING_EMERGENCY_BREAK = 2,
    DWRITE_WORD_WRAPPING_WHOLE_WORD = 3,
    DWRITE_WORD_WRAPPING_CHARACTER = 4
} DWRITE_WORD_WRAPPING;

typedef enum DWRITE_TRIMMING_GRANULARITY {
    DWRITE_TRIMMING_GRANULARITY_NONE = 0,
    DWRITE_TRIMMING_GRANULARITY_CHARACTER = 1,
    DWRITE_TRIMMING_GRANULARITY_WORD = 2
} DWRITE_TRIMMING_GRANULARITY;

typedef enum DWRITE_LINE_SPACING_METHOD {
    DWRITE_LINE_SPACING_METHOD_DEFAULT = 0,
    DWRITE_LINE_SPACING_METHOD_UNIFORM = 1,
    DWRITE_LINE_SPACING_METHOD_PROPORTIONAL = 2
} DWRITE_LINE_SPACING_METHOD;

typedef struct DWRITE_TRIMMING {
    DWRITE_TRIMMING_GRANULARITY granularity;
    UINT32 delimiter;
    UINT32 delimiterCount;
} DWRITE_TRIMMING;

typedef struct DWRITE_GLYPH_RUN DWRITE_GLYPH_RUN;

typedef struct DWRITE_INLINE_OBJECT_METRICS {
    FLOAT width;
    FLOAT height;
    FLOAT baseline;
    BOOL supportsSideways;
} DWRITE_INLINE_OBJECT_METRICS;

typedef struct DWRITE_TEXT_RANGE {
    UINT32 startPosition;
    UINT32 length;
} DWRITE_TEXT_RANGE;

typedef struct DWRITE_TEXT_METRICS {
    FLOAT left;
    FLOAT top;
    FLOAT width;
    FLOAT widthIncludingTrailingWhitespace;
    FLOAT height;
    FLOAT layoutWidth;
    FLOAT layoutHeight;
    UINT32 maxBidiReorderingDepth;
    UINT32 lineCount;
} DWRITE_TEXT_METRICS;

typedef struct DWRITE_HIT_TEST_METRICS {
    UINT32 textPosition;
    UINT32 length;
    FLOAT left;
    FLOAT top;
    FLOAT width;
    FLOAT height;
    UINT32 bidiLevel;
    BOOL isText;
    BOOL isTrimmed;
} DWRITE_HIT_TEST_METRICS;
#endif /* PDK_SKIP_DWRITE_TYPES */

/* ---- factory entry point ---- */
/* Omitted when the real <dwrite.h> is in scope, because it declares the
 * same function with a typed IUnknown parameter. */
#ifndef PDK_SKIP_DWRITE_TYPES
HRESULT WINAPI DWriteCreateFactory(DWRITE_FACTORY_TYPE factoryType,
                                   REFIID iid, PDK_IUnknown **factory);
#endif

typedef struct PDK_IDWriteFactory PDK_IDWriteFactory;
typedef struct PDK_IDWriteFactoryVtbl PDK_IDWriteFactoryVtbl;
typedef struct PDK_IDWriteTextFormat PDK_IDWriteTextFormat;
typedef struct PDK_IDWriteTextFormatVtbl PDK_IDWriteTextFormatVtbl;
typedef struct PDK_IDWriteTextLayout PDK_IDWriteTextLayout;
typedef struct PDK_IDWriteTextLayoutVtbl PDK_IDWriteTextLayoutVtbl;
typedef struct PDK_IDWriteInlineObject PDK_IDWriteInlineObject;
typedef struct PDK_IDWriteInlineObjectVtbl PDK_IDWriteInlineObjectVtbl;

struct PDK_IDWriteFactory { const PDK_IDWriteFactoryVtbl *lpVtbl; };
struct PDK_IDWriteTextFormat { const PDK_IDWriteTextFormatVtbl *lpVtbl; };
struct PDK_IDWriteTextLayout { const PDK_IDWriteTextLayoutVtbl *lpVtbl; };
struct PDK_IDWriteInlineObject { const PDK_IDWriteInlineObjectVtbl *lpVtbl; };

struct PDK_IDWriteFactoryVtbl {
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(PDK_IDWriteFactory *This, REFIID riid, void **ppvObject);
    ULONG (STDMETHODCALLTYPE *AddRef)(PDK_IDWriteFactory *This);
    ULONG (STDMETHODCALLTYPE *Release)(PDK_IDWriteFactory *This);
    void *GetSystemFontCollection;
    void *CreateCustomFontCollection;
    void *RegisterFontCollectionLoader;
    void *UnregisterFontCollectionLoader;
    void *CreateFontFileReference;
    void *CreateCustomFontFileReference;
    void *CreateFontFace;
    void *CreateRenderingParams;
    void *CreateMonitorRenderingParams;
    void *CreateCustomRenderingParams;
    void *RegisterFontFileLoader;
    void *UnregisterFontFileLoader;
    HRESULT (STDMETHODCALLTYPE *CreateTextFormat)(PDK_IDWriteFactory *This, const WCHAR *family_name, void *collection, DWRITE_FONT_WEIGHT weight, DWRITE_FONT_STYLE style, DWRITE_FONT_STRETCH stretch, FLOAT size, const WCHAR *locale, PDK_IDWriteTextFormat **format);
    void *CreateTypography;
    void *GetGdiInterop;
    HRESULT (STDMETHODCALLTYPE *CreateTextLayout)(PDK_IDWriteFactory *This, const WCHAR *string, UINT32 len, PDK_IDWriteTextFormat *format, FLOAT max_width, FLOAT max_height, PDK_IDWriteTextLayout **layout);
    void *CreateGdiCompatibleTextLayout;
    HRESULT (STDMETHODCALLTYPE *CreateEllipsisTrimmingSign)(PDK_IDWriteFactory *This, PDK_IDWriteTextFormat *format, PDK_IDWriteInlineObject **trimming_sign);
    void *CreateTextAnalyzer;
    void *CreateNumberSubstitution;
    void *CreateGlyphRunAnalysis;
};

struct PDK_IDWriteTextFormatVtbl {
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(PDK_IDWriteTextFormat *This, REFIID riid, void **ppvObject);
    ULONG (STDMETHODCALLTYPE *AddRef)(PDK_IDWriteTextFormat *This);
    ULONG (STDMETHODCALLTYPE *Release)(PDK_IDWriteTextFormat *This);
    HRESULT (STDMETHODCALLTYPE *SetTextAlignment)(PDK_IDWriteTextFormat *This, DWRITE_TEXT_ALIGNMENT alignment);
    HRESULT (STDMETHODCALLTYPE *SetParagraphAlignment)(PDK_IDWriteTextFormat *This, DWRITE_PARAGRAPH_ALIGNMENT alignment);
    HRESULT (STDMETHODCALLTYPE *SetWordWrapping)(PDK_IDWriteTextFormat *This, DWRITE_WORD_WRAPPING wrapping);
    void *SetReadingDirection;
    void *SetFlowDirection;
    void *SetIncrementalTabStop;
    HRESULT (STDMETHODCALLTYPE *SetTrimming)(PDK_IDWriteTextFormat *This, const DWRITE_TRIMMING *trimming, PDK_IDWriteInlineObject *trimming_sign);
    HRESULT (STDMETHODCALLTYPE *SetLineSpacing)(PDK_IDWriteTextFormat *This, DWRITE_LINE_SPACING_METHOD spacing, FLOAT line_spacing, FLOAT baseline);
    void *GetTextAlignment;
    void *GetParagraphAlignment;
    void *GetWordWrapping;
    void *GetReadingDirection;
    void *GetFlowDirection;
    void *GetIncrementalTabStop;
    void *GetTrimming;
    void *GetLineSpacing;
    void *GetFontCollection;
    void *GetFontFamilyNameLength;
    void *GetFontFamilyName;
    void *GetFontWeight;
    void *GetFontStyle;
    void *GetFontStretch;
    void *GetFontSize;
    void *GetLocaleNameLength;
    void *GetLocaleName;
};

struct PDK_IDWriteTextLayoutVtbl {
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(PDK_IDWriteTextLayout *This, REFIID riid, void **ppvObject);
    ULONG (STDMETHODCALLTYPE *AddRef)(PDK_IDWriteTextLayout *This);
    ULONG (STDMETHODCALLTYPE *Release)(PDK_IDWriteTextLayout *This);
    HRESULT (STDMETHODCALLTYPE *SetTextAlignment)(PDK_IDWriteTextLayout *This, DWRITE_TEXT_ALIGNMENT alignment);
    HRESULT (STDMETHODCALLTYPE *SetParagraphAlignment)(PDK_IDWriteTextLayout *This, DWRITE_PARAGRAPH_ALIGNMENT alignment);
    HRESULT (STDMETHODCALLTYPE *SetWordWrapping)(PDK_IDWriteTextLayout *This, DWRITE_WORD_WRAPPING wrapping);
    void *SetReadingDirection;
    void *SetFlowDirection;
    void *SetIncrementalTabStop;
    HRESULT (STDMETHODCALLTYPE *SetTrimming)(PDK_IDWriteTextLayout *This, const DWRITE_TRIMMING *trimming, PDK_IDWriteInlineObject *trimming_sign);
    HRESULT (STDMETHODCALLTYPE *SetLineSpacing)(PDK_IDWriteTextLayout *This, DWRITE_LINE_SPACING_METHOD spacing, FLOAT line_spacing, FLOAT baseline);
    void *GetTextAlignment;
    void *GetParagraphAlignment;
    void *GetWordWrapping;
    void *GetReadingDirection;
    void *GetFlowDirection;
    void *GetIncrementalTabStop;
    void *GetTrimming;
    void *GetLineSpacing;
    void *GetFontCollection;
    void *GetFontFamilyNameLength;
    void *GetFontFamilyName;
    void *GetFontWeight;
    void *GetFontStyle;
    void *GetFontStretch;
    void *GetFontSize;
    void *GetLocaleNameLength;
    void *GetLocaleName;
    void *SetMaxWidth;
    void *SetMaxHeight;
    void *SetFontCollection;
    void *SetFontFamilyName;
    void *SetFontWeight;
    void *SetFontStyle;
    void *SetFontStretch;
    void *SetFontSize;
    HRESULT (STDMETHODCALLTYPE *SetUnderline)(PDK_IDWriteTextLayout *This, BOOL underline, DWRITE_TEXT_RANGE range);
    void *SetStrikethrough;
    void *SetDrawingEffect;
    void *SetInlineObject;
    void *SetTypography;
    void *SetLocaleName;
    void *GetMaxWidth;
    void *GetMaxHeight;
    void *IDWriteTextLayout_GetFontCollection;
    void *IDWriteTextLayout_GetFontFamilyNameLength;
    void *IDWriteTextLayout_GetFontFamilyName;
    void *IDWriteTextLayout_GetFontWeight;
    void *IDWriteTextLayout_GetFontStyle;
    void *IDWriteTextLayout_GetFontStretch;
    void *IDWriteTextLayout_GetFontSize;
    void *GetUnderline;
    void *GetStrikethrough;
    void *GetDrawingEffect;
    void *GetInlineObject;
    void *GetTypography;
    void *IDWriteTextLayout_GetLocaleNameLength;
    void *IDWriteTextLayout_GetLocaleName;
    HRESULT (STDMETHODCALLTYPE *Draw)(PDK_IDWriteTextLayout *This, void *context, void *renderer, FLOAT originX, FLOAT originY);
    void *GetLineMetrics;
    HRESULT (STDMETHODCALLTYPE *GetMetrics)(PDK_IDWriteTextLayout *This, DWRITE_TEXT_METRICS *metrics);
    void *GetOverhangMetrics;
    void *GetClusterMetrics;
    void *DetermineMinWidth;
    HRESULT (STDMETHODCALLTYPE *HitTestPoint)(PDK_IDWriteTextLayout *This, FLOAT pointX, FLOAT pointY, BOOL *is_trailinghit, BOOL *is_inside, DWRITE_HIT_TEST_METRICS *metrics);
    HRESULT (STDMETHODCALLTYPE *HitTestTextPosition)(PDK_IDWriteTextLayout *This, UINT32 textPosition, BOOL is_trailinghit, FLOAT *pointX, FLOAT *pointY, DWRITE_HIT_TEST_METRICS *metrics);
    HRESULT (STDMETHODCALLTYPE *HitTestTextRange)(PDK_IDWriteTextLayout *This, UINT32 textPosition, UINT32 textLength, FLOAT originX, FLOAT originY, DWRITE_HIT_TEST_METRICS *metrics, UINT32 max_metricscount, UINT32 *actual_metricscount);
};

struct PDK_IDWriteInlineObjectVtbl {
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(PDK_IDWriteInlineObject *This, REFIID riid, void **ppvObject);
    ULONG (STDMETHODCALLTYPE *AddRef)(PDK_IDWriteInlineObject *This);
    ULONG (STDMETHODCALLTYPE *Release)(PDK_IDWriteInlineObject *This);
    HRESULT (STDMETHODCALLTYPE *Draw)(PDK_IDWriteInlineObject *This, void *client_drawingontext, void *renderer, FLOAT originX, FLOAT originY, BOOL is_sideways, BOOL is_rtl, PDK_IUnknown *drawing_effect);
    HRESULT (STDMETHODCALLTYPE *GetMetrics)(PDK_IDWriteInlineObject *This, DWRITE_INLINE_OBJECT_METRICS *metrics);
    void *GetOverhangMetrics;
    void *GetBreakConditions;
};

#endif /* PDK_SRC_GRAPHICS_DWRITE_C_H */
