#!/usr/bin/env python3
"""Generate the portable COM shim headers from the MinGW-w64 SDK headers.

The Windows SDK headers cannot serve as the single source of truth because
MSVC's C mode neither declares Direct2D vtables nor parses <dwrite.h> at all.
MinGW-w64's C mode does declare both, so it is used as the machine-checkable
reference: this script extracts the exact vtable layouts and emits

    src/graphics/d2d_c.h      Direct2D vtables (D2D1_* types come from <d2d1.h>)
    src/graphics/dwrite_c.h   DirectWrite types + vtables (self contained)
    src/graphics/iids_gen.h   every IID/CLSID the C sources need
    tools/shim_manifest.txt   interface -> ordered method names (drift baseline)

Everything is generated with the *same* flat layout for both toolchains, so no
source file outside these headers ever needs a compiler check.

Usage:
    python tools/gen_com_shim.py [--mingw-include DIR] [--check]

--check only verifies that the checked-in files are up to date.
"""
import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import shimparse as sp  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_INC = r"D:\_\3rd\mingw64-ucrt\x86_64-w64-mingw32\include"

BANNER = (
    "/* AUTO-GENERATED by tools/gen_com_shim.py -- do not edit by hand.\n"
    " * Regenerate with: python tools/gen_com_shim.py\n"
    " * Source of truth: MinGW-w64 C-mode SDK headers; layout is verified at\n"
    " * compile time by tests/shim_layout (MinGW) -- see plan.md 3.3.\n"
    " */\n"
)

# Names that look like interfaces but must keep their meaning.
KEEP_TOKENS = {"IID", "REFIID", "REFGUID", "REFCLSID"}
# MinGW spelling -> Windows SDK spelling.
TOKEN_ALIASES = {"WINBOOL": "BOOL"}

# DirectWrite methods that get a typed signature.  Everything else stays a
# size-only placeholder, which keeps the hand-free type surface small.
DWRITE_TYPED = {
    "QueryInterface", "AddRef", "Release",
    "CreateTextFormat", "CreateTextLayout", "CreateEllipsisTrimmingSign",
    "SetTextAlignment", "SetParagraphAlignment", "SetWordWrapping",
    "SetLineSpacing", "SetTrimming", "GetMetrics",
    "HitTestPoint", "HitTestTextPosition", "HitTestTextRange",
    "SetUnderline", "Draw",
}

RE_INTERFACE_TOKEN = re.compile(r"\b(?<!PDK_)(I[A-Z][A-Za-z0-9_]*)\b")
RE_DWRITE_TYPE = re.compile(r"\bDWRITE_[A-Za-z0-9_]+\b")


def die(msg):
    print("error: " + msg, file=sys.stderr)
    sys.exit(1)


def warn(msg):
    print("warning: " + msg, file=sys.stderr)


# --------------------------------------------------------------------------
# type rewriting
# --------------------------------------------------------------------------
def apply_aliases(text, hook=""):
    """Rewrite MinGW-only spellings to their Windows SDK equivalents.

    The copied type definitions contain struct fields (WINBOOL isTrimmed), not
    just vtable signatures, so the alias table has to run over the types as
    well -- MSVC has no WINBOOL at all.
    """
    for src, dst in TOKEN_ALIASES.items():
        text = re.sub(r"\b%s\b" % src, dst, text)
    for unknown in re.findall(r"\bWIN[A-Z][A-Za-z0-9_]*\b", text):
        if unknown not in ("WINAPI", "WCHAR", "WIN32_FIND_DATAW"):
            warn("MinGW-only token %r kept in %s; check it exists on MSVC"
                 % (unknown, hook or "types"))
    return text


def rewrite_types(text, owned, hook=""):
    """Map SDK interface names onto PDK types; unknown interfaces become void*."""

    def repl(m):
        name = m.group(1)
        if name in KEEP_TOKENS:
            return name
        if name in owned:
            return "PDK_" + name
        if name in TOKEN_ALIASES:
            return TOKEN_ALIASES[name]
        if name.startswith(("ID2D1", "IDWrite", "IWIC", "IDXGI", "IMF", "IMM",
                            "IAudio", "ISimple", "IStream", "IUnknown")):
            return "void"
        warn("unmapped interface-ish token %r in %s" % (name, hook))
        return "void"

    for src, dst in TOKEN_ALIASES.items():
        text = re.sub(r"\b%s\b" % src, dst, text)
    return RE_INTERFACE_TOKEN.sub(repl, text)

def normalise_decl(text):
    """Collapse whitespace while keeping the declaration readable."""
    text = " ".join(text.split())
    text = re.sub(r"\s*\*\s*", " *", text)
    text = text.replace(" * *", " **")
    text = re.sub(r"\(\s+", "(", text)
    text = re.sub(r"\s+\)", ")", text)
    return text.strip()


def build_member(ret, name, args, field, typed, owned, hook):
    if not typed:
        return "    void *%s;" % field
    ret = normalise_decl(rewrite_types(ret, owned, hook))
    args = normalise_decl(rewrite_types(args, owned, hook))
    return "    %s (STDMETHODCALLTYPE *%s)(%s);" % (ret, field, args)


def emit_interface(name, methods, typed_pred, owned):
    """Emit one flat vtable.  Returns (text, [(header_name, field_name), ...]).

    A few SDK vtables redeclare an inherited method with the *same* name in the
    same flat block (IDWriteTextLayout::GetFontCollection, for example), so the
    C field names have to be uniquified; the pair list lets the layout check
    know which slots can be compared by name against the SDK header.
    """
    lines = ["struct PDK_%sVtbl {" % name]
    used = {}
    pairs = []
    for ret, mname, args, _static in methods:
        used[mname] = used.get(mname, 0) + 1
        field = mname if used[mname] == 1 else "%s_%d" % (mname, used[mname])
        lines.append(build_member(ret, mname, args, field,
                                  typed_pred(name, mname), owned,
                                  "%s::%s" % (name, mname)))
        pairs.append((mname, field))
    lines.append("};")
    return "\n".join(lines), pairs


def forward_decls(names):
    out = []
    for n in names:
        out.append("typedef struct PDK_%s PDK_%s;" % (n, n))
        out.append("typedef struct PDK_%sVtbl PDK_%sVtbl;" % (n, n))
    return "\n".join(out)


def object_structs(names):
    out = []
    for n in names:
        out.append("struct PDK_%s { const PDK_%sVtbl *lpVtbl; };" % (n, n))
    return "\n".join(out)


# --------------------------------------------------------------------------
# DirectWrite plain types
# --------------------------------------------------------------------------
def index_dwrite_definitions(text):
    """Map type name -> (start, end, source_text) for dwrite.h definitions.

    Also returns member -> enum-owner so that a referenced enumerator pulls in
    the enum that declares it instead of being reported as missing.
    """
    defs = {}
    members = {}
    # typedef enum/struct NAME { ... } NAME;
    for m in re.finditer(r"typedef\s+(enum|struct)\s+(\w+)\s*\{", text):
        kind, name = m.group(1), m.group(2)
        depth = 1
        i = m.end()
        while i < len(text) and depth:
            if text[i] == "{":
                depth += 1
            elif text[i] == "}":
                depth -= 1
            i += 1
        semi = text.find(";", i)
        src = text[m.start():semi + 1]
        defs[name] = (m.start(), semi + 1, src)
        if kind == "enum":
            for mem in re.finditer(r"\b([A-Z][A-Z0-9_]*)\b\s*(?:=[^,}]*)?[,}]", src):
                members[mem.group(1)] = name
    # typedef BASE NAME;  /  typedef BASE *NAME;
    for m in re.finditer(r"typedef\s+([A-Za-z_][\w\s\*]*?)\s+(\w+)\s*;", text):
        base, name = normalise_decl(m.group(1)), m.group(2)
        if name.startswith("DWRITE_") and name not in defs:
            defs[name] = (m.start(), m.end(), text[m.start():m.end()])
    # #define NAME ...
    for m in re.finditer(r"^#define\s+(DWRITE_\w+)\s+([^\n]*)$", text, re.M):
        name = m.group(1)
        if name not in defs:
            defs[name] = (m.start(), m.end(), text[m.start():m.end()])
    return defs, members


def collect_dwrite_types(defs, members, seeds, external=()):
    """Transitive closure of DWRITE_* names referenced by the seeds.

    `external` names are already supplied by another SDK header in scope (for
    example <dcommon.h> provides DWRITE_MEASURING_MODE); they are accepted but
    never emitted.
    """
    external = set(external)
    needed = set()
    queue = list(seeds)
    missing = []
    while queue:
        name = queue.pop()
        if name in needed:
            continue
        if name in external:
            continue
        entry = defs.get(name)
        if entry is None:
            owner = members.get(name)
            if owner is not None:
                if owner not in needed:
                    queue.append(owner)
                continue
            missing.append(name)
            continue
        needed.add(name)
        for tok in RE_DWRITE_TYPE.findall(entry[2]):
            if tok != name and tok not in needed:
                queue.append(tok)
    return needed, missing


# --------------------------------------------------------------------------
# IIDs
# --------------------------------------------------------------------------
RE_DEFINE_GUID = re.compile(
    r"DEFINE_GUID\(\s*([A-Za-z_]\w*)\s*,\s*([^;]*?)\)\s*;", re.S
)
RE_DEFINE_GUIDSTRUCT = re.compile(
    r'DEFINE_GUIDSTRUCT\s*\(\s*"([0-9a-fA-F\-]+)"\s*,\s*([A-Za-z_]\w*)\s*\)\s*;'
)

# GUIDs that no include can define on MSVC: <ks.h>/<mmreg.h> spell them with
# DEFINE_GUIDSTRUCT, and MSVC's DEFINE_GUIDEX is always a plain declaration
# (it is not gated on INITGUID), so they have to come from our own iids_gen.h.
# MinGW-w64 publishes the GUID text literally, which is where these values are
# read from.
EXTRA_GUID_NAMES = [
    "KSDATAFORMAT_SUBTYPE_PCM",
    "KSDATAFORMAT_SUBTYPE_IEEE_FLOAT",
]

# The WASAPI and MMDevice GUIDs are the same story: MinGW's <mmdeviceapi.h> and
# <audioclient.h> use DEFINE_GUID, MSVC's use `EXTERN_C const IID name;` only, so
# a C translation unit that passes &IID_IAudioClient to Activate() has nothing to
# link against.  Emitting them here (and not including those headers from iids.c)
# keeps exactly one definition on both toolchains.
EXTRA_GUID_SOURCES = [
    ("mmdeviceapi.h", [
        "CLSID_MMDeviceEnumerator",
        "IID_IMMDeviceEnumerator",
        "IID_IMMNotificationClient",
    ]),
    ("audioclient.h", [
        "IID_IAudioClient",
        "IID_IAudioClient3",
        "IID_IAudioRenderClient",
    ]),
    # graphics/D2DContext.c creates the WIC factory from C, where there is no __uuidof, so
    # both the class id and the interface id have to be real definitions.  MSVC's
    # <wincodec.h> only declares them.
    ("wincodec.h", [
        "CLSID_WICImagingFactory",
        "IID_IWICImagingFactory",
    ]),
]


def guid_text_to_parts(text):
    """'00000001-0000-0010-8000-00aa00389b71' -> DEFINE_GUID argument list."""
    parts = text.split("-")
    if len(parts) != 5 or len(parts[3]) != 4 or len(parts[4]) != 12:
        die("unparsable GUID text %r" % text)
    a, b, c = parts[0], parts[1], parts[2]
    d = ",".join("0x" + parts[3][i:i + 2] for i in (0, 2))
    e = ",".join("0x" + parts[4][i:i + 2] for i in range(0, 12, 2))
    return "0x%s, 0x%s, 0x%s, %s, %s" % (a, b, c, d, e)


def index_guids(text):
    out = {}
    for m in RE_DEFINE_GUID.finditer(text):
        out[m.group(1)] = normalise_decl(" ".join(m.group(2).split()))
    return out


def index_guidstructs(text):
    out = {}
    for m in RE_DEFINE_GUIDSTRUCT.finditer(text):
        out[m.group(2)] = guid_text_to_parts(m.group(1))
    return out


# --------------------------------------------------------------------------
# main
# --------------------------------------------------------------------------
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--mingw-include", default=DEFAULT_INC)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    inc = args.mingw_include
    d2d_path = os.path.join(inc, "d2d1.h")
    dwrite_path = os.path.join(inc, "dwrite.h")
    for p in (d2d_path, dwrite_path):
        if not os.path.isfile(p):
            die("missing %s" % p)

    d2d_raw = sp.load_header(d2d_path)
    dwrite_raw = sp.load_header(dwrite_path)

    d2d_tables = {}
    for name in sp.SEED_D2D:
        d2d_tables[name] = sp.collect_interface(
            sp.find_vtbl_blocks(d2d_raw), name, warn)
    dwrite_tables = {}
    blocks_dw = sp.find_vtbl_blocks(dwrite_raw)
    for name in sp.SEED_DWRITE:
        dwrite_tables[name] = sp.collect_interface(blocks_dw, name, warn)

    owned_d2d = set(d2d_tables)
    owned_dwrite = set(dwrite_tables)
    # IUnknown is hand-written in graphics/Com.h and shared by both generated
    # headers, so neither of them may define it; it still has to be a known
    # "owned" name so signatures map it to PDK_IUnknown.
    owned = owned_d2d | owned_dwrite | {"IUnknown"}

    # ---- d2d_c.h -------------------------------------------------------
    order_d2d = [n for n in sp.SEED_D2D if n != "IUnknown"]
    d2d_parts = [BANNER]
    d2d_parts.append(
        "#ifndef PDK_SRC_GRAPHICS_D2D_C_H\n#define PDK_SRC_GRAPHICS_D2D_C_H\n")
    d2d_parts.append(
        "/* Flat PDK vtables for Direct2D.  D2D1_* structs and enums come from\n"
        " * the platform <d2d1.h>, which both MSVC C mode and MinGW C mode parse.\n"
        " * Method order/size is asserted against the SDK in tests/shim_layout. */\n")
    d2d_parts.append('#include "graphics/Com.h"\n')
    d2d_parts.append("#include <d2d1.h>\n")
    d2d_parts.append('#include "graphics/iids_gen.h"\n')
    d2d_parts.append('#include "graphics/dwrite_c.h"\n')
    d2d_parts.append("\n" + forward_decls(order_d2d) + "\n")
    d2d_parts.append("\n" + object_structs(order_d2d) + "\n")
    for name in order_d2d:
        text, _pairs = emit_interface(
            name, d2d_tables[name], lambda i, m: True, owned)
        d2d_parts.append("\n" + text + "\n")
    d2d_parts.append("\n#endif /* PDK_SRC_GRAPHICS_D2D_C_H */\n")
    d2d_text = "".join(d2d_parts)

    # ---- dwrite_c.h ----------------------------------------------------
    order_dw = [n for n in sp.SEED_DWRITE if n != "IUnknown"]
    # Types the Direct2D vtables mention are needed as well (DrawGlyphRun takes
    # a DWRITE_GLYPH_RUN).  Derive them from the text we just emitted so the two
    # headers cannot disagree.
    seed_types = {"DWRITE_FACTORY_TYPE"}
    seed_types |= set(RE_DWRITE_TYPE.findall(d2d_text))
    for name in order_dw:
        for ret, mname, argtext, _s in dwrite_tables[name]:
            if mname in DWRITE_TYPED:
                seed_types |= set(RE_DWRITE_TYPE.findall(argtext))
                seed_types |= set(RE_DWRITE_TYPE.findall(ret))
    # <dcommon.h> is pulled in by <d2d1.h> on both toolchains and already owns a
    # few DWRITE_* names; redefining them would be an error.
    dcommon_raw = ""
    dcommon_path = os.path.join(inc, "dcommon.h")
    if os.path.isfile(dcommon_path):
        dcommon_raw = sp.load_header(dcommon_path)
    dcommon_types = {m.group(2) for m in
                     re.finditer(r"typedef\s+(enum|struct)\s+(DWRITE_\w+)", dcommon_raw)}
    defs, members = index_dwrite_definitions(dwrite_raw)
    needed_types, missing_types = collect_dwrite_types(
        defs, members, sorted(seed_types), external=dcommon_types)
    if missing_types:
        die("dwrite.h is missing definitions for: %s" % ", ".join(sorted(missing_types)))
    supplied_by_dcommon = sorted(set(seed_types) & dcommon_types)
    ordered_types = sorted(needed_types, key=lambda n: defs[n][0])

    dw_parts = [BANNER]
    dw_parts.append(
        "#ifndef PDK_SRC_GRAPHICS_DWRITE_C_H\n#define PDK_SRC_GRAPHICS_DWRITE_C_H\n")
    dw_parts.append(
        "/* DirectWrite types and flat PDK vtables.\n"
        " * <dwrite.h> is deliberately NOT included: MSVC C mode cannot parse it\n"
        " * (dwrite.h:4704 uses C++ inheritance), so both toolchains consume these\n"
        " * definitions instead.  They are extracted verbatim from the MinGW-w64\n"
        " * header by tools/gen_com_shim.py and cross-checked against the real\n"
        " * <dwrite.h> by tests/shim_layout.\n"
        " *\n"
        " * Define PDK_SKIP_DWRITE_TYPES before including this header when the real\n"
        " * <dwrite.h> is already in scope (that is what tests/shim_layout does). */\n")
    dw_parts.append('#include "graphics/Com.h"\n')
    dw_parts.append('#include "graphics/iids_gen.h"\n')
    dw_parts.append("\n#ifndef PDK_SKIP_DWRITE_TYPES\n")
    dw_parts.append("/* ---- types (verbatim from MinGW-w64 <dwrite.h>) ---- */\n")
    if supplied_by_dcommon:
        dw_parts.append("/* supplied by <dcommon.h>: %s */\n"
                        % ", ".join(supplied_by_dcommon))
    for name in ordered_types:
        dw_parts.append("\n" + apply_aliases(defs[name][2].strip(), name) + "\n")
    dw_parts.append("#endif /* PDK_SKIP_DWRITE_TYPES */\n")
    dw_parts.append("\n/* ---- factory entry point ---- */\n")
    dw_parts.append("/* Omitted when the real <dwrite.h> is in scope, because it declares the\n"
                    " * same function with a typed IUnknown parameter. */\n")
    dw_parts.append("#ifndef PDK_SKIP_DWRITE_TYPES\n")
    dw_parts.append(
        "HRESULT WINAPI DWriteCreateFactory(DWRITE_FACTORY_TYPE factoryType,\n"
        "                                   REFIID iid, PDK_IUnknown **factory);\n")
    dw_parts.append("#endif\n")
    dw_parts.append("\n" + forward_decls(order_dw) + "\n")
    dw_parts.append("\n" + object_structs(order_dw) + "\n")
    for name in order_dw:
        text, _pairs = emit_interface(
            name, dwrite_tables[name],
            lambda i, m: m in DWRITE_TYPED, owned)
        dw_parts.append("\n" + text + "\n")
    dw_parts.append("\n#endif /* PDK_SRC_GRAPHICS_DWRITE_C_H */\n")
    dwrite_text = "".join(dw_parts)

    # ---- iids_gen.h ----------------------------------------------------
    guids = {}
    guids.update(index_guids(d2d_raw))
    guids.update(index_guids(dwrite_raw))
    for ks_name in ("mmreg.h", "ksmedia.h", "ks.h"):
        ks_path = os.path.join(inc, ks_name)
        if os.path.isfile(ks_path):
            guids.update(index_guidstructs(sp.load_header(ks_path)))
    for header, names in EXTRA_GUID_SOURCES:
        header_path = os.path.join(inc, header)
        if not os.path.isfile(header_path):
            die("missing %s, which owns %s" % (header, ", ".join(names)))
        found = index_guids(sp.load_header(header_path))
        for name in names:
            if name not in found:
                die("%s has no DEFINE_GUID for %s" % (header, name))
            guids[name] = found[name]
    wanted = set()
    for name in owned_d2d:
        wanted.add("IID_" + name)
    for name in owned_dwrite:
        wanted.add("IID_" + name)
    wanted.discard("IID_IUnknown")
    wanted |= set(EXTRA_GUID_NAMES)
    for _header, names in EXTRA_GUID_SOURCES:
        wanted |= set(names)
    iid_parts = [BANNER]
    iid_parts.append(
        "#ifndef PDK_SRC_GRAPHICS_IIDS_GEN_H\n#define PDK_SRC_GRAPHICS_IIDS_GEN_H\n")
    iid_parts.append(
        "/* GUIDs the C sources reference by name.  'iids.c' is the single TU\n"
        " * that defines INITGUID before including this header, so every symbol\n"
        " * has exactly one definition and no import library is required. */\n")
    iid_missing = []
    for name in sorted(wanted):
        value = guids.get(name)
        if value is None:
            # Not every interface has a DEFINE_GUID in the MinGW headers (for
            # example IID_ID2D1HwndRenderTarget is only a library symbol).  We
            # never need those, because the project obtains interfaces from
            # typed creation methods rather than QueryInterface; a missing GUID
            # only becomes an error if something actually references it.
            iid_missing.append(name)
            continue
        iid_parts.append("DEFINE_GUID(%s, %s);\n" % (name, value))
    if iid_missing:
        warn("no DEFINE_GUID available for: %s" % ", ".join(iid_missing))
    iid_parts.append("\n#endif /* PDK_SRC_GRAPHICS_IIDS_GEN_H */\n")
    iids_text = "".join(iid_parts)

    # ---- tests/shim_layout checks --------------------------------------
    # sizeof() equality is the strong assertion: the SDK's own C-mode vtable is
    # built by the compiler from <d2d1.h>/<dwrite.h>, while ours comes from the
    # parser above, so any missed or invented method shows up immediately.
    # Per-method offsetof() pins the order of the methods declared in the
    # interface's own block (inherited slots are covered by the size check plus
    # the base's own checks).  See plan.md 3.3.
    blocks_all = {}
    blocks_all.update(sp.find_vtbl_blocks(d2d_raw))
    blocks_all.update(blocks_dw)
    chk = [BANNER]
    chk.append(
        "/* Included by tests/shim_layout after <d2d1.h>, <dwrite.h> and\n"
        " * PDK_SKIP_DWRITE_TYPES + graphics/d2d_c.h.  MinGW only. */\n")
    chk.append("#include <stddef.h>\n")
    for name in sp.SEED_D2D + sp.SEED_DWRITE:
        if name == "IUnknown":
            continue
        flat = d2d_tables.get(name) or dwrite_tables.get(name)
        base, own = sp.parse_vtbl(name, blocks_all[name], warn)
        _text, pairs = emit_interface(
            name, flat, lambda i, m: True, owned)
        seen = set()
        unique_own = []
        for mname, field in pairs[len(flat) - len(own):]:
            if mname in seen:
                continue  # the SDK block redeclares the name; offsetof is ambiguous
            seen.add(mname)
            unique_own.append((mname, field))
        chk.append("\n/* %s: %d slots */\n" % (name, len(flat)))
        chk.append(
            '_Static_assert(sizeof(PDK_%sVtbl) == sizeof(%sVtbl), "%s vtable size");\n'
            % (name, name, name))
        for mname, field in unique_own:
            chk.append(
                "typedef char pdk_off_%s_%s[offsetof(PDK_%sVtbl, %s) "
                "== offsetof(%sVtbl, %s) ? 1 : -1];\n"
                % (name, mname, name, field, name, mname))
    checks_text = "".join(chk)

    # ---- manifest ------------------------------------------------------
    man = []
    for name in sp.SEED_D2D + sp.SEED_DWRITE:
        tbl = d2d_tables.get(name) or dwrite_tables.get(name)
        man.append("%s %d" % (name, len(tbl)))
        for _ret, mname, _args, _s in tbl:
            man.append("  " + mname)
    manifest = "\n".join(man) + "\n"

    outputs = {
        os.path.join(ROOT, "src", "graphics", "d2d_c.h"): d2d_text,
        os.path.join(ROOT, "src", "graphics", "dwrite_c.h"): dwrite_text,
        os.path.join(ROOT, "src", "graphics", "iids_gen.h"): iids_text,
        os.path.join(ROOT, "tools", "shim_manifest.txt"): manifest,
        os.path.join(ROOT, "tests", "shim_layout", "ShimLayoutChecks.h"): checks_text,
    }

    dirty = []
    for path, text in outputs.items():
        old = None
        if os.path.isfile(path):
            with open(path, encoding="utf-8") as fh:
                old = fh.read()
        if old != text:
            dirty.append(path)
            if not args.check:
                os.makedirs(os.path.dirname(path), exist_ok=True)
                with open(path, "w", encoding="utf-8", newline="\n") as fh:
                    fh.write(text)
    if args.check:
        if dirty:
            for p in dirty:
                print("out of date: %s" % os.path.relpath(p, ROOT))
            sys.exit(1)
        print("shim headers up to date")
    else:
        for p in dirty:
            print("wrote %s" % os.path.relpath(p, ROOT))
        if not dirty:
            print("shim headers already up to date")


if __name__ == "__main__":
    main()
